### ISSUE TITLE
Add setting to allow HTML

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-vscode#10]
It is good to be togglable enable or disable HTML as a configuration of extension. It would work as same as `--html` option in Marp CLI.

Feedbacked to https://github.com/marp-team/marp-vscode/issues/4#issuecomment-468853244.

**Comment by yhatt** [comment]
[An updated VS Code 1.32 is no longer required reload when installing Marp for VS Code.](https://code.visualstudio.com/updates/v1_32#_no-reload-required-when-installing-markdown-extensions) But internally, it means that adding toggleable settings based on an unique Marp instance become be harder.

I have to re-think a logic to toggle HTML by setting, and Marp Core may require update.

**Comment by yhatt** [comment]
Shipped with v0.0.6 🚢

**Comment by eric-burel** [comment]
That's a great feature, could you add a line about this option in the Readme?
It's very hard to find doc about HTML support in Markdown, either in Marp or with other tools. It's usually supported but it's not always obvious, I had to dig until I found this issue.

Or maybe the fact that HTML is supported should be specified in Marpit doc directly?

**Comment by yhatt** [comment]
You're right. Inspite of my fault, I got tired to response troubles caused by missed writing this documentation.

Continue in #98.
