### ISSUE TITLE
Last slide visually shifted in HTML export

### ISSUE THREAD

**Issue by badcat** [marp-team/marp-vscode#101]
Really love marp for vscode - Thank you.

I noticed that the last slide on the generated HTML export is always slightly shifted vertically in the browser.  It looks lke the "Marp Core's Browser" JS is getting put inside the last slide's SVG.  If the JS was moved outside the last SVG (perhaps just before the closing body tag), then the preview appears correct without any visual position shifting.

tested on:
macOS 10.14 - Chrome latest, Safari 13.0.2, Firefox 70.0.1

Example MD and HTML attached:
[marp-shift.zip](https://github.com/marp-team/marp-vscode/files/3853223/marp-shift.zip)

**Comment by yhatt** [comment]
Thanks for your catching of details.

JS injection to the last SVG slide has implemented in recent Marp Core. This behavior is for dealing with Marp CLI's bug reported by power-user (marp-team/marp-cli#168), but it seems to get small visual regression as you see (VS Code preview is disabled this injection so would make clear the difference).

I'm sure moving `<script>` to the outside of SVG would work fine, but we have to improve architectures of Marp ecosystem to get it.

**Comment by yhatt** [comment]
Fixed in v0.11.2.
