### ISSUE TITLE
How to change the font of the preview? 

### ISSUE THREAD

**Issue by Spacekoki** [marp-team/marp-vscode#108]
```
---
marp: true
---

<style>
.slide{
font-family: 'Noto Sans JP', serif !important;
}
</style>
```
If I changed the font like this, the exported pdf was the font but the preview was not.
I also added ` "markdown.preview.fontFamily": "Meiryo UI", ` in the settings.json of VScode, but the preview was not.

**Comment by yhatt** [comment]
Same question as marp-team/marp-cli#161. Probably you are seeing a styling reference for [the outdated Marp app](https://yhatt.github.io/marp/).

Use `section` selector instead of `.slide`.

```html
<style>
section {
  font-family: 'Noto Sans JP', serif !important;
}
</style>
```

> *NOTE: GitHub issue tracker is not suitable place to question. Refer to [our support guideline](https://github.com/marp-team/.github/blob/master/SUPPORT.md#question).*

**Comment by Spacekoki** [comment]
Solved. Thank you very much!
