### ISSUE TITLE
How to highlight words?

### ISSUE THREAD

**Issue by Spacekoki** [marp-team/marp-vscode#109]
I read [this guideline](https://github.com/marp-team/.github/blob/master/SUPPORT.md#question). Therefore I tried to put this question on StackOverflow, but I needed over 1500 reputations to place a new tag "marp".  Unfortunately, I don't have over 1500 reputations, so please forgive me.
How to highlight words on marp? I used `==abc==` when I was using the desktop app but doesn't work on VS Code edition.

**P.S.** I want to highlight words like the Gaia theme on the default theme.

**Comment by yhatt** [comment]
`==abc==` for the outdated Marp app is [meaning as same as `<mark>abc</mark>`.](https://github.com/markdown-it/markdown-it-mark#readme) You can use `<mark>` tag by enabling HTML in VS Code preference.

**Comment by Spacekoki** [comment]
> `==abc==` for the outdated Marp app is [meaning as same as `<mark>abc</mark>`.](https://github.com/markdown-it/markdown-it-mark#readme) You can use `<mark>` tag by enabling HTML in VS Code preference.

How can I enable HTML?

**Comment by yhatt** [comment]
https://github.com/marp-team/marp-vscode#enable-html-in-marp-markdown
