### ISSUE TITLE
feature request: show only 1 slide in preview and add next/pre slide key

### ISSUE THREAD

**Issue by fastfading** [marp-team/marp-vscode#112]
feature request: 
show only 1 slide in preview 
add next/pre slide key/button in preview
navigate the markdown code automatically according to the preview page

**Comment by yhatt** [comment]
We have already tested in [`one-by-one-preview` branch](https://github.com/marp-team/marp-vscode/tree/one-by-one-preview), but we got it is difficult because of lacked VS Code API for Markdown preview extension to get current document and cursor.

**Comment by fastfading** [comment]
maybe you can refer to vscode-reveal extension,  I saw they have implement
this feature.
https://github.com/evilz/vscode-reveal

Yuki Hattori <notifications@github.com> 于2019年12月18日周三 下午3:12写道：

**Comment by yhatt** [comment]
Our extension has a bit different purpose from [vscode-reveal](https://github.com/evilz/vscode-reveal). We are focusing to preview and conversion Marp slides, and not very to present.

Probably you may be interested to #87 if you wanted to present Marp slide just in VS Code.

**Comment by fastfading** [comment]
people use marp , wants to replace ppt with markdown.
Not only for presentation but also for modification in the mean while.

if presentation and  modification separated.
why we use this tool ,  why not use ppt directly.
for ppt always need changed, may by many people.
it is not convenient to have a markdown copy and a ppt copy

this tool is only one step closer to replace ppt now .

Yuki Hattori <notifications@github.com> 于2019年12月18日周三 下午4:57写道：

**Comment by yhatt** [comment]
As I mentioned #87 is the first step toward that.

---

BTW at least this extension is not aiming to super one. We've learned in [the old app](https://yhatt.github.io/marp/) (integrated environment) what [people have own different opinion about requirements to create slide deck](https://github.com/yhatt/marp/issues?q=is%3Aissue+is%3Aclosed). Our tools, just a small part of Marp ecosystem, are designed to leave most of requirements and keep simple.

If you felt lack something, you can create a better extension or app based on Marp ecosystem (or [Marpit framework](https://marpit.marp.app/)) by yourself.

**Comment by fastfading** [comment]
Sorry , I am not a front-end developer. Hardly contribute on this.
From User's view
vscode-reveal extension is quite good in UI design. 
However ,   I don't like reveal.js and its coding style.


you did a great work.  thank you for your effort.
thank you for your reply and patience.
