### ISSUE TITLE
Plantuml support

### ISSUE THREAD

**Issue by czhiling** [marp-team/marp-vscode#116]
Thank you very much for developing  Marp-vscode.

I would like to ask whether it is possible to render plantuml in Marp -vscode? 

Plantuml is powerful yet elegant. It's supported by the extension markdown preview enhanced and  some others. It is very useful for us to render many different chart without leaving vscode. 

Zhiling

**Comment by yhatt** [comment]
Marp CLI can plug third-party plugin ([markdown-it-plantuml](https://github.com/gmunguia/markdown-it-plantuml)) so you can convert Marp Markdown + PlantUML through [Marp CLI](https://github.com/marp-team/marp-cli) within VS Code integrated terminal.

> ```js
> const { Marp } = require('@marp-team/marp-core')
> 
> module.exports = {
>     engine: opts => new Marp(opts).use(require('markdown-it-plantuml'))
> }
> ```
>
> *— https://github.com/marp-team/marp-core/issues/112*

Marp for VS Code cannot preview the result of Markdown conversion with plugin. We are scaring to make complex rendering logic and huge security hole.

But I know some user want to customize rendering engine of Marp in VS Code (e.g. https://github.com/marp-team/marp-core/issues/136#issuecomment-566509967) We might work for supporting plugin if security concerns were resolved.

**Comment by czhiling** [comment]
Thank for you very much for the prompt reply. I will try Marp CLI.
