### ISSUE TITLE
Exported HTML slide deck does not come with <title> tag

### ISSUE THREAD

**Issue by flamanta** [marp-team/marp-vscode#117]
Hi, first of all thank you so much for developing Mapp! This is the most intuitive Markdown-based slide deck editor I have used so far. A few hours in and I have finished my slide deck with minimum use of my mouse!

I exported my slide deck to both HTML and PDF, but the HTML slide deck does not come with a HTML `<title>` tag. It would be good if the Marp VSCode extension could auto-detect (or allow the user to specify the title of the HTML slide deck).

Possibly related issues:
- [marpteam/marp-cli#131](https://github.com/marp-team/marp-cli/issues/131): Detect the title of deck from first slide when title option is not passed

**Comment by yhatt** [comment]
You can use [Marp CLI's `title` global directive](https://github.com/marp-team/marp-cli#by-global-directives) until implementing marp-team/marp-cli#131.

```markdown
---
marp: true
title: Title for your deck
---
```

**Comment by flamanta** [comment]
I see, thank you for your help! :)
