### ISSUE TITLE
strange text colors

### ISSUE THREAD

**Issue by sgandon** [marp-team/marp-vscode#12]
I have finally switched to the Marp Next framework.
I am using VSCode to edit and preview my markdown but the rendering is the same when I generate htlm or pdf.
There are some strange color in the text that I cannot explain.

![](https://github.com/sgandon/Git-sandbox/raw/master/marpit_strange_text_colors.png)

the configuration is like this in my markdown
```
---
marp: true
size: 16:9
theme: gaia
backgroundColor: #0C2D4D
color: white
paginate: true
---
```

**Comment by yhatt** [comment]
They are caused by auto language detection of syntax highlight for code fence. It can disable highlight by specifying the language as `text`.

    ```text
    helm init
    ```

See also https://github.com/yhatt/marp/issues/81.

**Comment by sgandon** [comment]
thanks a lot, this works as expected.
