### ISSUE TITLE
Possible to add VSCode options in marp-vscode to allow passing arguments when exporting?

### ISSUE THREAD

**Issue by zhangchuck** [marp-team/marp-vscode#121]
Would it be possible to add an option in the marp-vscode extension (e.g., similar to `markdown.marp.toggleMarpPreview`) that would allow users to specify additional options to be passed to marp-cli? e.g., `markdown.marp.additionCLIoptions`?

This would save the trouble of doing this outside of marp-vscode.

(From #4, looks like marp-cli is being used to export PDF/HTML; #86 indicates that the vscode markdown **preview** engine will not be changed.

It would be useful to be able to export with some of the marp-cli options, even if it is not shown in the marp-vscode preview, e.g., be able to export with the `bespoke.progress` option mentioned in the marp-cli README.)

**Comment by yhatt** [comment]
If we have decided to work for that, I think we will add an option for power-user, to toggle whether using Marp CLI configuration file placed at the root of current workspace: `.marprc` `marp.config.js` etc...

Marp for VS Code is giving an importance to the exactly matched preview with the output, and I suppose that the most of users expect that. So VS Code extension will have to explain that the configuration file is working only for an export command, and the added toggle option should be disabled by default.

**Comment by zhangchuck** [comment]
Thanks for the response. I think the changes wouldn't have to be too major, given how the code is setup right now. I took a stab at trying to put in the functionality (draft PR), but I've never written Typescript before and couldn't get the dev environment setup properly, so don't have a fully working solution. Hopefully helpful in reducing the costs of adding the feature (if you decide to go down that route).

**Comment by yhatt** [comment]
VS Code team is working now for creation trusted workspace concept. Custom Marp CLI configuration support should be based on that to protect users from any malicious (e.g. tampered Marp module including in the repository on the Web).

Continue the issue on #194.
