### ISSUE TITLE
command 'markdown.marp.showQuickPick' not found

### ISSUE THREAD

**Issue by noraj** [marp-team/marp-vscode#122]
The app extension takes forever to install, does-it try to install chromium or something heavy?

As it was never ending I closed vs-code and opened it again, the Marp extension was displayed as installed but when I try to toggle to  Marp preview I have an error: `command 'markdown.marp.showQuickPick' not found`.

I have installed Marp vscode extension from the marketplace.
Does the extension is standalone or requires Marp-CLI installed?

I have installed it on other machines some months ago and it was working. I don't remember doing more steps.

**Comment by noraj** [comment]
## Info

```
Name: Marp for VS Code
Id: marp-team.marp-vscode
Description: Create slide deck written in Marp Markdown on VS Code
Version: 0.12.0
Publisher: Marp team
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=marp-team.marp-vscode
```

**Comment by noraj** [comment]
I tried installing uninstalling many times withotu success but then I tried manually.

```
$ code --install-extension /tmp/marp-team.marp-vscode-0.12.0.vsix 
Installing extensions...
(node:24377) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:24377) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'marp-team.marp-vscode-0.12.0.vsix' was successfully installed.
```

It took 3 sec and now it works. I downloaded the vsix from the marketplace, I don't understand it should be the same.

**Comment by yhatt** [comment]
Perhaps an error caused by incomplete extraction of VSIX package. A time taking for installation depends on the performance such as network and file I/O. For example, failing may be remarkable if you connected to network through proxy server.

If you are using vsix file that was downloaded from `Download Extension` link in marketplace, it must be same as an installed extension through UI.

Our extension do *never* download/install any browsers because we are using Chrome installed by user. On the other hand, Marp CLI has included in the extension. It means you don't need to install standalone CLI to use Marp extension, but we might have a bit heavier package size than other extensions.

**Comment by noraj** [comment]
> A time taking for installation depends on the performance such as network and file I/O. For example, failing may be remarkable if you connected to network through proxy server.

Weird, I have an unfiltered fiber access and direct access to internet and a high performance SSD. When I download the VSIX directly from the Marketplace had it instantly and the installed took less than 3 sec in CLI, IDK why when installing form the GUI it was taking ages.

> If you are using vsix file that was downloaded from `Download Extension` link in marketplace, it must be same as an installed extension through UI.

Yes I agree.



> Our extension do _never_ download/install any browsers because we are using Chrome installed by user. On the other hand, Marp CLI has included in the extension. It means you don't need to install standalone CLI to use Marp extension, but we might have a bit heavier package size than other extensions.

Ok, I first thought the log time was due to some compiling or huge dependency retrieving but it seems it was a random bug from VSCode extension installer.

As I successfully installed it in the end I'll close for now.
