### ISSUE TITLE
color support

### ISSUE THREAD

**Issue by JiahaoYao** [marp-team/marp-vscode#126]
I wonder can we use html color in the marp, I tested that but find the color is not rendering. 

```
<span style="color:red">abc</span>
```

**Comment by yhatt** [comment]
Just turn on **"Markdown > Marp: Enable HTML"** (`markdown.marp.enableHtml`) in [VS Code preferences](https://code.visualstudio.com/docs/getstarted/settings).

NOTE: It might bring some security risk. See also our [README.md](https://github.com/marp-team/marp-vscode#enable-html-in-marp-markdown).

**Comment by JiahaoYao** [comment]
Thank @yhatt
