### ISSUE TITLE
How do I change the indentation depth in code blocks for tabs in the output?

### ISSUE THREAD

**Issue by melgu** [marp-team/marp-vscode#128]
The default indentation for tabs in Marp output is huge (just like in the GitHub preview). Can I change that to be just the equivalent of 4 spaces instead of 8?

```swift
0 Tabs
	1 Tab
		2 Tabs
			3 Tabs
```

**Comment by yhatt** [comment]
8 spaces is [an initial value of `tab-size` CSS style](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size) for tabs. In Marp, you can modify the number of spaces by inline `<style>` tag ([Style tweaking](https://marpit.marp.app/theme-css?id=tweak-style-through-markdown) is an available feature inherited from [our base framework, Marpit](https://marpit.marp.app/)).

````markdown
<style>
pre {
  tab-size: 4;
}
</style>

```
0 Tabs
	1 Tab
		2 Tabs
			3 Tabs
```
````

<img width="572" alt="tab-size" src="https://user-images.githubusercontent.com/3993388/75945266-0ef5e200-5edd-11ea-9c49-5c9f86a21bdb.png">

**Comment by melgu** [comment]
Thank you so much!
