### ISSUE TITLE
failed to export local png figures to pptx and pdf

### ISSUE THREAD

**Issue by JaylanLiu** [marp-team/marp-vscode#134]
the png figures are inserted to my .md file either with absolute path or relative path,  and I can see the figures  have rendered correctly in the right preview window.

```
# Example
Here is the absolute path citing of local figure.
![](/mnt/c/Users/liujilong/OneDrive/python_code/tmp/a.png)

---

# Example2
Here is the relative path citing of local figure.
 ![](tmp.jpg) 

---
```
![image](https://user-images.githubusercontent.com/14886277/78675796-267b1d00-7918-11ea-9cbb-b326f2fcf1b6.png)

However, when I export the slides to pptx or pdf using `Marp: Export slide deck`, the figures are always missing. 
![image](https://user-images.githubusercontent.com/14886277/78675956-5cb89c80-7918-11ea-9b65-4ba1ab4d57cb.png)

But it works when I insert online  figures as URL. So I think it is a bug

**Comment by yhatt** [comment]
First, let me make clear that the absolute path from drive root cannot preview in Marp for VS Code by VS Code's security reason (See also #68). You should have seen no image specified by the absolute path.

But it looks strange that images that are shown in the preview have not rendered in the exported file. Could you share the log outputted to the developer console while exporting? (Open developer tool from `Help > Toggle Developer Tools` and run export command)

**Comment by JaylanLiu** [comment]
Thanks for your reply!
First, yes, the png inserted using absolute path cannot be seen in the preview.

Second, the log is
```
resourceLoader.ts:44 Error: Unable to read file 'vscode-remote://wsl+ubuntu-18.04/vscode-resource?{"requestResourcePath":"/home/lo/python_code/tmp/mnt/c/Users/liujilong/OneDrive/python_code/tmp/a.png"}' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/lo/python_code/tmp/mnt/c/Users/liujilong/OneDrive/python_code/tmp/a.png')
    at _.doReadAsFileStream (fileService.ts:457)
    at processTicksAndRejections (internal/process/task_queues.js:85)
```

The correct path is "/mnt/c/Users/liujilong/OneDrive/python_code/tmp/a.png". However, it was "/home/lo/python_code/tmp/mnt/c/Users/liujilong/OneDrive/python_code/tmp/a.png" which in the log.

**Comment by yhatt** [comment]
I guess there is your markdown at `/home/lo/python_code/tmp/xxxxxx.md`. In this case, VS Code can never access to the parent directory of `/home/lo/tmp/python_code` for preventing some malicious attack by extensions, such as sniffing local data. (https://github.com/microsoft/vscode/issues/75039) Thus, you have to give up to use absolute path.

The error is throwing from VS Code, so I suppose the export command will work by removing a line of the image referenced by absolute path.

**Comment by JaylanLiu** [comment]
Thank you. I have understood why the absolute path failed.

Below I test with the relative path and I think I have found the problem. 

My  initial `/home/lo/python_code/` directory is the symbolic link to `/mnt/c/Users/liujilong/OneDrive/python_code/`. When I put my attached marp directory  as `/mnt/c/Users/liujilong/OneDrive/python_code/marp` and run 'Marp: Export slide deck' in this directory with the output "marpinsymbolicdirectory.pptx" , the figure is still missing in the pptx file with the console log:
![image](https://user-images.githubusercontent.com/14886277/78903472-c1f1c680-7aad-11ea-9281-3fefb025b005.png)

However, when I coped the marp directory to another non-symbolic link directory as `/home/lo/tmp/marp`, and run 'Marp: Export slide deck' it worked correctly with the output "marpinlocal.pptx".

Since the symbolic-link scene is not common,  I think this issue can be closed.

[marp.zip](https://github.com/marp-team/marp-vscode/files/4456564/marp.zip)

**Comment by yhatt** [comment]
Thank you for providing details. As you may find out well, the export command seems not to be able to render image resources that requires resolving symlink.

I suppose should treat as an issue of an integrated Marp CLI rather than Marp for VS Code.

**Comment by lawliet89** [comment]
I encountered the same issue and I fixed it by accessing the directory from `/mnt/xxx` instead of the symlink.

**Comment by yhatt** [comment]
Close for housekeeping.
