### ISSUE TITLE
How can I use mardown-it plugins in Marp for VSC

### ISSUE THREAD

**Issue by dhruva81** [marp-team/marp-vscode#135]
Hi Marpit team

I am trying to use markdown-it-container and markdown-it-sup extensions in Marp for Visual Studio Code.  But I am not able to do this. I have searched on Google and YouTube, but I am not able to find any tutorial on how to integrate this functionality.

Please help how can I integrate other markdown-it extensions in Marp for VSC.

Thank you

**Comment by kongdd** [comment]
I found https://github.com/yzhang-gh/vscode-markdown-container here. 
Any chance to support it?
