### ISSUE TITLE
How to use Latex Package in Marp App

### ISSUE THREAD

**Issue by dhruva81** [marp-team/marp-vscode#136]
Hi Marp Team

This is not an issue. It is a question.
How can I use Latex packages in Marp app for visual studio code.
On Googling, I have found following code. But it is not working.

`header-includes: 
    - \usepackage{bbm} 
    - \usepackage{lipsum}
    - \usepackage{amsmath}   `

Thank You

**Comment by yhatt** [comment]
You can't. `header-includes` is [the feature of Pandoc](https://pandoc.org/MANUAL.html#variables-set-automatically), and not Marp. We are not based on LaTeX so any packages for LaTeX cannot use.

> **NOTICE:** GitHub issue tracker is for tracking development issues and not for questions. We recommend to ask in [StackOverflow](http://stackoverflow.com/) community first. Read [our support guideline](https://github.com/marp-team/.github/blob/master/SUPPORT.md#question) too.
