### ISSUE TITLE
Exported pptx cannot be edited

### ISSUE THREAD

**Issue by kanglinyao** [marp-team/marp-vscode#139]
Exported pptx cannot be edited by powerpoint.

**Comment by yhatt** [comment]
It's an expected result. In general, tools generating web-based presentation cannot create a reliable and editable pptx. (e.g. Marp, GitPitch Pro) Refer to the reason explained in https://github.com/marp-team/marp-cli/issues/166#issuecomment-536827067.

> Marp focuses to keep beautiful looking slides regardless of the kind of conversion. Rendering images is the best way for that. Creating editable PPTX is very hard because it's like re-creation of HTML rendering engine. Perhaps it would be much larger project than Marp.
> 
> If you want editable PPTX, we recommend to convert exported PDF into PPTX by Adobe Acrobat. However, I suppose the reproducibility of output is not good even if this. (different fonts, incorrect shadow rendering, etc...)
> 
> |Current PPTX generation<br />(Not editable / Perfect reproducibility)|PDF -> PPTX by Adobe Acrobat<br />(Editable / Incorrect renderings)|
> |:---:|:---:|
> |![marp-pptx](https://user-images.githubusercontent.com/3993388/65928915-bb1d3380-e43a-11e9-8129-12c182240c46.png)|![adobe-acrobat](https://user-images.githubusercontent.com/3993388/65928937-cff9c700-e43a-11e9-8cb3-245edfa55ed4.png)|

_Originally posted by @yhatt in https://github.com/marp-team/marp-cli/issues/166#issuecomment-536827067_

**Comment by CyrusYip** [comment]
You can convert pdf to pptx via [ilovepdf](https://www.ilovepdf.com/pdf_to_powerpoint). I hope this helps you.

**Comment by aimerneige** [comment]
You can convert output PDF to PPTX by Adobe Acrobat.

**Comment by tdb-alcorn** [comment]
Just dropping this here as it worked well for me: https://www.adobe.com/acrobat/online/pdf-to-ppt.html

My only issue was the fonts were a little off.

**Comment by kongdd** [comment]
whether it is possible using acrobat.exe to convert pdf to pptx in the cmd mode?

**Comment by yhatt** [comment]
@kongdd 

> No. As already described in [marp-team/marp#82](https://github.com/orgs/marp-team/discussions/82), I have never seen FLOSS CLI tool for converting PDF to PPTX. Even if exists, it would take the same approach as Marp.
> 
> In addition, there is really few choice even in the commercial product: [Adobe community has answered simply "No" for command line solution of PDF -> PPTX via Adobe Acrobat.](https://community.adobe.com/t5/acrobat/how-to-get-xi-pro-to-convert-pdf-to-ppt-at-command-prompt/m-p/8976329) As far as I saw, any alternative products (Solid Converter, Smallpdf desktop, Foxit PDF editor, Nitro PDF, etc...) also have not the command line interface.
>
> _&mdash; https://github.com/marp-team/marp-cli/issues/141#issuecomment-876469348_

**Comment by fastfading** [comment]
> @kongdd
> 
> > [Adobe community has answered simply "No" for command line solution of PDF -> PPTX via Adobe Acrobat.](https://community.adobe.com/t5/acrobat/how-to-get-xi-pro-to-convert-pdf-to-ppt-at-command-prompt/m-p/8976329) As far as I saw, any alternative products (Solid Converter, Smallpdf desktop, Foxit PDF editor, Nitro PDF, etc...) also have not the command line interface.
> > _— [marp-team/marp-cli#141 (comment)](https://github.com/marp-team/marp-cli/issues/141#issuecomment-876469348)_

https://github.com/ashafaei/pdf2pptx
this is the best tool I found 
could it be integrated into vscode marp plugin ？

**Comment by kongdd** [comment]
@fastfading 
> I convert all the slides to high-quality image files first, and then push them into a Powerpoint project as a slide. <https://github.com/ashafaei/pdf2pptx>

So the exported ppt still cannot be edited.

**Comment by pvanand07** [comment]
@kanglinyao 
1. pdf->ocr pdf  https://www.ilovepdf.com/ocr-pdf
2. ocr pdf --> ppt https://www.ilovepdf.com/pdf_to_powerpoint
This works well

**Comment by yhatt** [comment]
We have created a draft pull request for Marp CLI, to add experimental feature for making editable PPTX powered by LibreOffice. (marp-team/marp-cli#626)

After this feature was shipped, we would be able to implement the same feature in VS Code.

**Comment by yhatt** [comment]
**UPDATE:** [Marp for VS Code v3.1.0](https://github.com/marp-team/marp-vscode/releases/tag/v3.1.0) has been added an experimental `markdown.marp.pptx.editable` option to export an editable PPTX. By setting this as `on` or `smart`, Marp for VS Code will try to make PPTX editable.
https://github.com/marp-team/marp-vscode#experimental-settings
