### ISSUE TITLE
HTML tag stoped to work

### ISSUE THREAD

**Issue by otobrzo** [marp-team/marp-vscode#140]
Marp is very nice and I really love to use it.

Recently the html tag 

```
<video  width="800" controls  autoplay muted loop style="display:block; margin:0 auto;">
<source src="video.mp4" type="video/mp4">
</video>
```

stopped to work.

**Comment by yhatt** [comment]
Transferred from Marp CLI ▶️ Marp for VS Code 🚚 

Re-confirm VS Code Preference. Marp for VS Code requires to turn on HTML in the setting (at your own risk).

![](https://user-images.githubusercontent.com/3993388/57288647-d76bad00-70f4-11e9-8810-0d8987363f8b.png)

**Comment by otobrzo** [comment]
Oh, sorry, I forgot this...
