### ISSUE TITLE
Export to all formats unable to find images midway through

### ISSUE THREAD

**Issue by teopb** [marp-team/marp-vscode#141]
I think this might be related to #134 but I don't think my problem has anything to do with symlinks so I started a new issue. Hope that is correct. I am using the VScode extension and my slideshow renders correctly in the preview. However when exporting after the 12th slide (4th image) the images no longer get rendered. This is true for all export formats. I thought this may be do to the symlink problem but all are local files. I was initially working in a Dropbox folder but making a local copy shows the same behavior. I thought it may have something to do with file name or type but even if you use an image that correctly rendered above it will not render after that point in the document. I tried using the CLI directly and got the same output and warnings. 

<img width="780" alt="Screen Shot 2020-04-27 at 8 55 13 PM" src="https://user-images.githubusercontent.com/6201937/80442809-feedf380-88ca-11ea-81e1-f42c662dcbca.png">

**Comment by yhatt** [comment]
Images are resolved with the same rule regardless of N-th slide page, so losing all images from midway is hard to expect.

Try opening exported _HTML in browser_ and check out console in developer tools. You may see more specific errors.

**Comment by teopb** [comment]
Thank you for the response. I realize the Nth side thing was silly but it was the only pattern I could recognize. But turns out I had been inserting a leading forward slash in the paths from that point forward. The VScode preview apparently plays fine with that but the export, reasonably, does not.
