### ISSUE TITLE
Consider changing the default export type into HTML

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-vscode#142]
A time to consider changing the default export type into HTML is coming.

## Background

Marp for VS Code was supposed that users familiar to the manner of export in [the classic Marp app](https://yhatt.github.io/marp/), so the default export type is PDF.

However, PDF is for *the portable document* as shown by its name. It should suit for the handout of the deck, but hard to use dynamic contents such as animation GIF and CSS Animations in the real presentation. In addition, user would lose a chance to get more powerful features provided by [Marp CLI's `bespoke` template](https://github.com/marp-team/marp-cli#bespoke-template-default) due to the default setting.

I think we should no longer need trapped in the past because a half of year has passed from stopped publishing the old Marp app.

This change might make losing portability of exported deck, but we have already provided an option to change the default export type (`markdown.marp.exportType`). User can set PDF export as default from the preference, and also choose PDF type in save dialog if necessarry.

### Pros

- Become easily to use powerful features by [Marp CLI `bespoke` template](https://github.com/marp-team/marp-cli#features): Fragmented list, presenter view, and presenter note.
- All kind of media will work: GIF animation, CSS Animations, `<video>` and `<audio>` (by enabling HTML).
- Fastest to export and not depending on Chrome / Chromium.

### Cons

- May confuse exist users expecting to export PDF.
- Doesn't ensure portabillity especially if using local resources.
  - Relative path for assets would break easily if exported HTML into the different place from the original Markdown. (Originally Marp CLI recommend to use online assets rather than locals)
  - [Web Bundles](https://web.dev/web-bundles/) experimental proposal would help to make portabllity with keeping interactivities of the deck. (https://github.com/marp-team/marp-cli/issues/159#issuecomment-553266548)

**Comment by aywi** [comment]
> * Doesn't ensure portabillity especially if using local resources.
>   * Relative path for assets would break easily if exported HTML into the different place from the original Markdown. (Originally Marp CLI recommend to use online assets rather than locals)
>   * [Web Bundles](https://web.dev/web-bundles/) experimental proposal would help to make portabllity with keeping interactivities of the deck. ([marp-team/marp-cli#159 (comment)](https://github.com/marp-team/marp-cli/issues/159#issuecomment-553266548))

For slides, since most of the possible local resources are images, printing images to Base64 may be a simpler solution. An example is Markdown All in One: <https://github.com/yzhang-gh/vscode-markdown/pull/172>.

**Comment by yhatt** [comment]
@aywi Probably we are not going to take Base64 encoding. Replacing `<img>` may be helpful partially but would miss many other use cases: `<figure>`, `<picture>`, images defined by CSS (global and inline style), and dynamic generated image elements by JavaScript in Markdown. Marp hopes to provide go-straight solution to user so the best is "all or nothing". I think incomplete and partial conversions will make some confusions.

**Comment by yhatt** [comment]
Marp team has decided to put on hold this. If changed, a following problem may make big confusion to users.

> - Doesn't ensure portabillity especially if using local resources

PDF is still the best choice: portable, easy to take, and uninfluenced by network status.
