### ISSUE TITLE
Highlight several lines in code block and add line number

### ISSUE THREAD

**Issue by alphamodel** [marp-team/marp-vscode#146]
Some markdown dialects support highlight several lines in the code block using syntax like below to highlight line 1 and line 3-5:

```python{1,3-5}
import os
import sys
if __name__=="__main__":
  print(sys.path)
  print("Hello"
```
Is there similar functionality in Marp?

BTW, is there anyway to show line number in the code block?

Thanks!

**Comment by yhatt** [comment]
You can extend syntax as you like. Try using [Marp CLI's functional engine](https://github.com/marp-team/marp-cli#functional-engine) + [markdown-it-highlight-lines](https://github.com/egoist/markdown-it-highlight-lines) plugin.

**Comment by alphamodel** [comment]
@yhatt Thanks a lot. So essentially, this is not supported in vscode extension. Need to go through `marp-cli` manually?

**Comment by yhatt** [comment]
Yep, Marp for VS Code cannot plug to enhance syntax due to potential security reason: https://github.com/marp-team/marp-vscode/issues/135#issuecomment-611275071.

**Comment by alphamodel** [comment]
Thanks for promptly reply! This issue can be close. Have a nice day!

**Comment by run27017** [comment]
> You can extend Marp syntax as you like. Try using [Marp CLI's functional engine](https://github.com/marp-team/marp-cli#functional-engine) + [markdown-it-highlight-lines](https://github.com/egoist/markdown-it-highlight-lines) plugin.

But how to? I use following code but it not work:

```javascript
const { Marp } = require('@marp-team/marp-core')
const highlightLines = require('markdown-it-highlight-lines')

module.exports = (opts) => new Marp(opts).use(highlightLines)
```

**Comment by yhatt** [comment]
@run27017 As explained in [README of markdown-it-highlight-lines](https://github.com/egoist/markdown-it-highlight-lines#usage), it's important to add custom style for `.highlighted-line` by your own because the plugin is just parsing highlight syntax like `` ```js {1,2,4-5} ``.

````markdown
---
theme: default
---

```js {1,2,4-5}
function foo() {
  return bar().then((res) => {
    return res.doSomething()
  })
}
```

<style>
.highlighted-line {
  background-color: #ff0;
  display: block;
  margin: 0 -16px;
  padding: 0 16px;
}
</style>
````

![](https://user-images.githubusercontent.com/3993388/105611655-d5caa700-5df9-11eb-9dd2-9eb0374b6b6b.png)
