### ISSUE TITLE
Do not preview local image file

### ISSUE THREAD

**Issue by dabrain34** [marp-team/marp-vscode#149]
I have been trying many syntax but displaying a local image at the same level of the markdown is not working:

`![image](./image.png)` with image.png at the same level

**Comment by yhatt** [comment]
We could not reproduce the reported issue. [Need more informations](https://github.com/marp-team/.github/blob/master/CONTRIBUTING.md#bug-report).

![● markdown md - marp - Visual Studio Code 2020_06_24 19_32_37](https://user-images.githubusercontent.com/3993388/85540757-594ccb80-b652-11ea-9f9b-f3080ff6c1fd.png)

**Comment by dabrain34** [comment]
Can you please tell me the minimum vscode version to use ?

![Screenshot from 2020-06-24 13-10-33](https://user-images.githubusercontent.com/9320752/85546560-4e2b7880-b61d-11ea-8928-eb031aa14413.png)

**Comment by yhatt** [comment]
Marp for VS Code will work with [VS Code >= 1.14.0](https://github.com/marp-team/marp-vscode/blob/master/package.json#L33). But in this case, I think a using version is not related.

These are some hints to reveal the cause of broken image.

- Opening developer tools *for preview pane* may be helpful to find the cause of issue: <kbd>Ctrl+Shift+P</kbd> -> `Developer: Open Webview Developer Tools`.
- Try to reproduce with disabled all other installed extensions. The other Markdown extension might be preventing to load local images.
- Please check whether the image preview is working with VS Code's regular Markdown preview by setting `marp: false`. It might be a general issue of VS Code if the image could not see in both of regular preview and Marp.

**Comment by dabrain34** [comment]
Thank you @yhatt , I finally found the root cause who was a bad naming coupled with a beginner level in marp.

Now I know the `Ctrl+Shift+P -> Developer: Open Webview Developer Tools` and it is very helpful !!!

On the other hand do you know where I could find resources using marp (slides) to get inspired, because i'm trying to resize logos or place text in the middle and I'm a bit confused of the syntax in the documentation ?

**Comment by yhatt** [comment]
I see. 😉

We still don't have official resources for guidance to Marp users. We have [the documentation of a basis framework Marpit](https://marpit.marp.app) but _it's for the developer._

We have a plan to create helpful resources for creating the awesome deck at https://marp.app/, and you can get inspired from community in the meantime.

- See ["Examples" section on Marp repository](https://github.com/marp-team/marp#examples). We are culating [maintainer's starter](https://github.com/yhatt/marp-cli-example) and some use cases by community that got agreement to introduce in our repo.
- [Find out the slide deck repositories from community that depends on Marp](https://github.com/marp-team/marp-core/network/dependents) (Marp Core). Many people is creating slides with Marp and you would be able to get inspired from them.
