### ISSUE TITLE
Cannot export to pdf with math

### ISSUE THREAD

**Issue by perrying** [marp-team/marp-vscode#150]
Thanks for the great work!

Now, I have the following issue:
when I export the following markdown file to pdf, I have "Failure to export. Marp CLI throwed error with exit code 1.":
```
---
marp: true
---
# test

$A$
```

But, the marp-preview in vscode renders $A$, and the following markdown file can be exported to pdf:
```
---
marp: true
---
# test
```
Here is the screenshot
<img width="1005" alt="issue" src="https://user-images.githubusercontent.com/19153297/86455923-4a55cf80-bd5c-11ea-89be-0aa17fafefda.png">

any thoughts?

env:
- mac osx 10.15.5
- vscode 1.46.1
- marp for vscode 0.14.0

**Comment by yhatt** [comment]
We could not reproduce it. What is showing in developer console after exporting? (<kbd>Ctrl/Cmd+Shift+P</kbd> :arrow_right: `Developer: Toggle Developer Tools`)

**Comment by perrying** [comment]
Thanks for your reply!
but it was fixed when I tried the export this morning.
I don't know the cause (I haven't even taken action such as rebooting.), but it works now.

**Comment by yhatt** [comment]
OK. I guess jsDelivr CDN temporally met outage, or blocked resolving KaTeX resources by network/proxy in Chrome.
https://cdn.jsdelivr.net/npm/katex@latest/dist/fonts/

If you met this issue frequently, try to switch math lib from KaTeX into MathJax in VS Code setting (`markdown.marp.mathTypesetting`). It should require no online resources for math.
