### ISSUE TITLE
Drag'n drop support for images

### ISSUE THREAD

**Issue by Jarzka** [marp-team/marp-vscode#159]
Hi

Drag'n dropping images directly in Markdown text would make it much easier to include images in Markdown files. Would it be possible to implement such a functionality?

**Comment by yhatt** [comment]
Probably it cannot. It seems that VS Code does not feel like to add custom handling for D&D: https://github.com/microsoft/vscode/issues/5240

Instead, "Copy image and paste to Markdown" is available by the other extension. [Paste Image](https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image) extension is the most popular but [you can find out something suitable for you in marketplace](https://marketplace.visualstudio.com/search?term=markdown%20insert%20image&target=VSCode&category=All%20categories&sortBy=Relevance).

Marp for VS Code must [do only one thing well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well): Helping creation of Marp presentation. We are not going to take others and should be supplied by other extensions.

**Comment by Jarzka** [comment]
Thanks for the advice.

**Comment by yhatt** [comment]
FYI: D&D support for Markdown is finally coming to the latest VS Code 1.67.
https://code.visualstudio.com/updates/v1_67#_markdown-drop-into-editor-to-create-link

**Comment by ElecTreeFrying** [comment]
https://marketplace.visualstudio.com/items?itemName=ElecTreeFrying.drag-import-relative-path

![markdown-demo](https://user-images.githubusercontent.com/19801459/185787474-500342f1-782f-4846-b33a-6579502d75ff.gif)
