### ISSUE TITLE
Unable to install your extension in Codium

### ISSUE THREAD

**Issue by JOduMonT** [marp-team/marp-vscode#169]
Hi;
I would like to use your Marp-VSCode in Codium (a fork of Code) but it is not working

`ext install marp-team.marp-vscode` is not found

**Comment by yhatt** [comment]
Duplicate of VSCodium/vscodium#439?

**Comment by MSSandroid** [comment]
So marp has no intention to publish the extension on open-vsx.org?

**Comment by yhatt** [comment]
@MSSandroid Please open new issue to request. We would work for (automated) publishing to open-vsx if we confirmed it's in demand.
