### ISSUE TITLE
Poor synchronization of Markdown preview

### ISSUE THREAD

**Issue by fonnesbeck** [marp-team/marp-vscode#173]
In the current release of the extension, the Markdown preview does not sync the location of the preview with that of the editor very well. It starts out in the correct spot when the preview is enabled, but even a little scrolling around makes the preview lose its place. My deck is currently relatively small (about 15 slides). 

Running VS Code 1.49.2 on Linux.

**Comment by yhatt** [comment]
For now, Marp extension is depending on VS Code's Markdown preview and leaves the most of sync logic to VS Code. So if you feel it has poor synchronization, you might feel like the same also in regular Markdown preview.

VS Code is trying to sync scroll position in each Markdown views to _the top of view_. Notice that is not based on caret position.

Marp cannot move sync position because may break regular features in VS Code (e.g. `markdown.preview.doubleClickToSwitchToEditor`). It may be a good step to request improved synchronization into [microsoft/vscode](https://github.com/microsoft/vscode) if you have an idea of sync that is looks good.

**Comment by fonnesbeck** [comment]
Thanks for the clarification. I have not noticed synchronization problems with standard markdown, but with a Marp presentation it is often very badly synchronized (i.e. several slides away from what is being edited). Perhaps it depends on the elements that are included on the slides(?). Happy to close this if nothing can be done.

**Comment by yhatt** [comment]
FYI attach the diagram how to sync Markdown preview in VS Code. There is the baseline to sync preview on the top of window.

![](https://user-images.githubusercontent.com/3993388/95347956-7901ba00-08f8-11eb-86e7-72c5ab13b455.png)

In this case, the preview shows unintended slide pages even if you were editting the content in page 10.

**Comment by fonnesbeck** [comment]
Thanks for the helpful screen shot. This is definitely not the behavior I am observing. For example, if I scroll down to an arbitrary place in my presentation, I see the following:

![Screenshot 2020-10-07 at 8 31 21 PM](https://user-images.githubusercontent.com/81476/95405031-48138c00-08dc-11eb-87b9-f957934a42c0.png)

The editor shows a slide somewhere in the middle of the presentation, yet the preview is actually showing the last two slides. Even stranger, if I scroll down slightly, I hops to an entirely different part of the presentation (closer to the start of the deck):

![Screenshot 2020-10-07 at 8 35 16 PM](https://user-images.githubusercontent.com/81476/95405162-a50f4200-08dc-11eb-90f4-192a9d6375a8.png)

Hence, my confusion about the expected sync behavior.

**Comment by yhatt** [comment]
Thanks for details to discover what happening. It probably looks like a trouble caused by specific Markdown contents as you said. Could you share a reproducible Markdown for debug?

**Comment by fonnesbeck** [comment]
I can share a Google Drive folder with one if you like.

**Comment by yhatt** [comment]
Close for housekeeping. 🧹 

I've found out VS Code's core problem about scroll sync with the extension: https://github.com/microsoft/vscode/issues/126640. Currently I've applied a (very hacky) workaround in #252, and shipped in marp-vscode v1.0.3 and later. I hope this problem has resolved.
