### ISSUE TITLE
Marp vscode preview behind corporate proxy on Ubuntu

### ISSUE THREAD

**Issue by esgn** [marp-team/marp-vscode#174]
Hi,

I'm pretty sure I'm having some kind of a problem with marp presentation preview in vscode behind a corporate proxy. Local images are correctly displayed but all the online images won't show up.
Is there some way to force a network proxy in preview ? 
For the record : http_proxy and https_proxy env vars are correctly defined and works fine with the rest of vscode.

Thanx in advance,

**Comment by yhatt** [comment]
Marp is never touching to VS Code's proxy so online images in the Markdown preview are supposed to be shown via proxy as same as a regular preview. If an image was shown in the rest of VS Code including Regular Markdown preview, Marp preview also should be able to show.

Could you check out why not shown images by following these steps? 

1. Open Marp Markdown file and its Marp preview
2. Open command palette by <kbd>Ctrl+Shift+P</kbd>, and choose "Developer: Open Webview Developer Tools"
3. Select "Network" tab
4. Edit markdown to refresh Marp preview
5. Back to developer tools and see a network request for the image

**Comment by yhatt** [comment]
Close the issue for housekeeping, because it's not likely caused by Marp.

Please re-open if confirmed that is Marp-specific problem by explained process.
