### ISSUE TITLE
How do I show all bullet points on a slide at once in generated HTML slide deck?

### ISSUE THREAD

**Issue by jc-camosun** [marp-team/marp-vscode#180]
Currently, I have to press the right arrow key to make each bullet point appear on the slide. Is there a directive to alternatively have them all show up on the slide immediately when a slide is shown? In other words, arrow keys scroll through entire slides not just bullet points.

**Comment by yhatt** [comment]
Duplicate of marp-team/marp-cli#102.

> Just replace the bullet * into - in list item

Refer to https://marpit.marp.app/fragmented-list.

**Comment by jc-camosun** [comment]
Great thanks. Sorry I missed that in the docs.
