### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by reyespinosa1996** [marp-team/marp-vscode#189]
- Issue Type: `Bug`
- Extension Name: `marp-vscode`
- Extension Version: `0.17.0`
- OS Version: `Linux x64 5.3.18-lp152.57-default`
- VSCode version: `1.52.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 11767,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "marp-team.marp-vscode",
				"_lower": "marp-team.marp-vscode"
			},
			"activationEvent": "onLanguage:markdown"
		}
	},
	"runtimeErrors": []
}
```

**Comment by yhatt** [comment]
Outdated: We cannot determine the action for this issue with just the pasted info. To reopen this, let us know your expected behavior and actual behavior.

Also refer to the contribution guideline for Marp team: https://github.com/marp-team/.github/blob/master/CONTRIBUTING.md#bug-report
