### ISSUE TITLE
Code block not loading in WSL Ubuntu 18.04

### ISSUE THREAD

**Issue by TheodoreChu** [marp-team/marp-vscode#190]
I'm using the demo text at [marp.app](https://marp.app). It works normally on Windows 10:
![image](https://user-images.githubusercontent.com/22967798/103116930-124d8c00-461d-11eb-8190-5f3869cc42c2.png)

It doesn't work on WSL Ubuntu 18.04 LTS:
![image](https://user-images.githubusercontent.com/22967798/103117013-6f494200-461d-11eb-828f-f047a7b3cd46.png)

Version: `0.17.0` installed globally

**Comment by yhatt** [comment]
I could not reproduce in my VS Code with remote in WSL Ubuntu. Need extra information:

- VS Code version and details (You can copy information from `Help -> About`)
- Details about error occured in WebView pane for preview (Open preview pane and `Ctrl + Shift + P -> "Developer: Open WebView Developer Tools" -> Console tab)

**Comment by TheodoreChu** [comment]
I can't reproduce the issue today either, but here is my VS Code version and details:
```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

Maybe the issue went away after I restarted my computer (and thus WSL and VS Code).

I'm not sure if this is related, but this is the error that I found in the console:
```
VM77 index.js:formatted:710 Uncaught TypeError: Cannot assign to read only property 'className' of object '#<SVGSVGElement>'
    at t.ActiveLineMarker._markActiveElement (VM77 index.js:formatted:710)
    at t.ActiveLineMarker._update (VM77 index.js:formatted:703)
    at t.ActiveLineMarker.onDidChangeTextEditorSelection (VM77 index.js:formatted:699)
    at VM77 index.js:formatted:336
```

**Comment by yhatt** [comment]
It may be a one-shot trouble by [VS Code remote extension](https://github.com/microsoft/vscode-remote-release) or unstable network specific, not a Marp's issue.

Close this for housekeeping Because the reported issue would not affect to use Marp.
