### ISSUE TITLE
Mermaid support

### ISSUE THREAD

**Issue by PaddiM8** [marp-team/marp-vscode#191]
Taken from [the website](https://mermaid-js.github.io/mermaid/#/):
> Mermaid lets you represent diagrams using text and code. This simplifies maintaining complex diagrams. It is a Javascript based diagramming and charting tool that renders Markdown-inspired text definitions to create and modify diagrams dynamically. The main purpose of Mermaid is to help Documentation catch up with Development.

I think this would be a great feature to have in marp, any thoughts? Using this in markdown is already possible in for example Joplin. It would fit really well here, since you can do things like this: [![](https://mermaid.ink/img/eyJjb2RlIjoicGllIHRpdGxlIFBldHMgYWRvcHRlZCBieSB2b2x1bnRlZXJzXG4gICAgXCJEb2dzXCIgOiAzODZcbiAgICBcIkNhdHNcIiA6IDg1XG4gICAgXCJSYXRzXCIgOiAxNVxuICAgICAgICAgICAgIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoicGllIHRpdGxlIFBldHMgYWRvcHRlZCBieSB2b2x1bnRlZXJzXG4gICAgXCJEb2dzXCIgOiAzODZcbiAgICBcIkNhdHNcIiA6IDg1XG4gICAgXCJSYXRzXCIgOiAxNVxuICAgICAgICAgICAgIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)  

as easily as this:
```
pie title Pets adopted by volunteers
    "Dogs" : 386
    "Cats" : 85
    "Rats" : 15
```

**Comment by PaddiM8** [comment]
Nvm, an issue exists in marp-core

**Comment by yhatt** [comment]
Duplicate of marp-team/marp-core#139.

**Comment by yhatt** [comment]
We have many workarounds:

- https://github.com/yhatt/marp/issues/125#issuecomment-509485121
- Marp CLI + customized engine + markdown-it-mermaid
- Use Markdown snippet that have generated in https://mermaid-js.github.io/mermaid-live-editor/

**Comment by PHHENS** [comment]
Dear Marp Next Developper,
It would be helpful to support mermaid directly in" Marp for vscode" simply with
```mermaid
 ...
```
Same thing for svgbob.
This combination could give very efficient graphical support directly into marp.
Thanks a lot

**Comment by yhatt** [comment]
@PHHENS Please read https://github.com/yhatt/marp/issues/125#issuecomment-461355723: There are some technically problems for real-time preview support to mermaid.js and Marp team has given up it. Marp ecosystem has a useful plugin system and we leave mermaid.js support to Marp developer community.

**Comment by ProbablePrime** [comment]
@yhatt 

With [Marp-core V5, now supporting mermaid](https://github.com/marp-team/marp-core/issues/139#issuecomment-5215744949), I'm trying to understand the path that it must take to make it into this extension. Is there an issue or milestone that covers this?

I'd be willing to contribute to support this upgrade if required. This extension was PERFECT for my needs except for this issue.

Happy to help push it along if that's appropriate.

Thank you for making such an awesome tool.

**Comment by yhatt** [comment]
Updates will be rolled out from the bottom up, starting with the stable core, followed by the CLI and then VS Code.

[The core update also includes breaking changes that may break existing slides.](https://github.com/orgs/marp-team/discussions/625) So we plan to take enough time 2-3 months for that Markdown and theme authors can test the new core with CLI.

**Comment by ProbablePrime** [comment]
Thank you for the update, that helps me understand your flow.
