### ISSUE TITLE
latex and header/footer directives in v0.17.1

### ISSUE THREAD

**Issue by jonghyunharrylee** [marp-team/marp-vscode#200]
Thank you for maintaining this great app! It seems that latex ($eqn$) and header/footer directives conflict when they are used at the same time. I am using Win10 and marp-vscode still works well with 0.17.0.

**Comment by yhatt** [comment]
I've tried to make reproduce your situation in v0.17.1 but it does not see like bringing confliction. What the input and the output you are expecting?

<img width="991" src="https://user-images.githubusercontent.com/3993388/107327014-be750480-6aef-11eb-88df-1ad654c61054.png">

**Comment by yhatt** [comment]
Thanks! I think the updation of marp-team/marp-core#212 has made something bad. Please keep using v0.17.0 if you required to create slides with math + header and footer. Sorry for the inconvinience!

**Comment by yhatt** [comment]
@jonghyunharrylee Fixed in [Marp Core v1.4.3](https://github.com/marp-team/marp-core/releases/tag/v1.4.3), and has bundled into the latest extension release [v0.17.2](https://github.com/marp-team/marp-vscode/releases/tag/v0.17.2). Please update your extension to the latest!

**Comment by jonghyunharrylee** [comment]
With v0.17.2 It is working as expected. Thank you!!
