### ISSUE TITLE
export to pptx feature not working properly

### ISSUE THREAD

**Issue by jehunseo** [marp-team/marp-vscode#202]
![w:256 image](https://user-images.githubusercontent.com/31786318/107874741-008eb380-6eff-11eb-9206-8897683cecd1.png)![w:256  image](https://user-images.githubusercontent.com/31786318/107874734-f79de200-6efe-11eb-9923-d5fbb6f29886.png)

left image is preview from vscode, right image is exported ppt file.
i wrote an markdown document with
```
---
marp: true
color: black
---
```
and used feature export slide deck/to pptx
but the exported pptx file has all pages with first slide contents.

my vscode version is : 1.53.2
and extensions about markdown is : 
[Paste Image](https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image)
[Markdown All in One]( https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)

**Comment by yhatt** [comment]
Thanks for your report. I think [a breaking change of Puppeteer v7](https://github.com/puppeteer/puppeteer/releases/tag/v7.0.0) containing in [the latest Marp CLI](https://github.com/marp-team/marp-cli/releases) has affected to PPTX export. Do you have installed Google Chrome Canary (v90)?

**Comment by jehunseo** [comment]
nope, I only use MS Edge 88.0.705.68 64bit browser.

**Comment by yhatt** [comment]
I could not confirm that thing in the conversion through MS Edge 88.0.705.68 for macOS 64bit. But anyway we have to catch up the updation of DevTools for Chromium flavored browser in marp-team/marp-cli#325.

**Comment by pigbayspy** [comment]
I had same problem. All slide pages remain the same as the first page. But it's ok in server mode

**Comment by ConnorKirk** [comment]
For anyone else who encounters this issue, I was able to work around it by downloading an earlier release of marp, then using that from the command line to generate the pptx export.

**Comment by yhatt** [comment]
Fixed in [Marp CLI v0.23.3](https://github.com/marp-team/marp-cli/releases/tag/v0.23.3).

The current VS Code extension is still using outdated CLI v0.23.2. I'm going to update dependency.

**Comment by yhatt** [comment]
Confirmed that has fixed in the latest update [v0.17.3](https://github.com/marp-team/marp-vscode/releases/tag/v0.17.3). Try to update your extension!
