### ISSUE TITLE
preview,not load theme

### ISSUE THREAD

**Issue by nzk1912** [marp-team/marp-vscode#204]
vscode1.53.2
Marp for VS Code 0.17.2

open the markdown preview window, without rendering according to marp's theme. Yesterday was ok, but something suddenly went wrong today. I don't know where the problem is? Can you give some ideas for analyzing the problem?
The content of markdown is definitely correct.
```
---

marp: true
size: 16:9
theme: gaia
paginate: true
style: |
    section a {
        font-size: 30px;
    }

---
# title
```

**Comment by yhatt** [comment]
If became not to work suddenly, the most likely problem is confliction against other extensions. Please confirm to reproduce the problem by disabling Markdown extensions other than Marp.

**Comment by nzk1912** [comment]
perfect
