### ISSUE TITLE
Table formatting seems to be no longer working in preview and exported HTML

### ISSUE THREAD

**Issue by rayburgemeestre** [marp-team/marp-vscode#206]
Hi there,

This is the issue:

![image](https://user-images.githubusercontent.com/498257/112138868-50cdf500-8bd2-11eb-969e-e5d1428399df.png)

This is how it looks with `marp: false`

![image](https://user-images.githubusercontent.com/498257/112138928-63e0c500-8bd2-11eb-9391-8b3048c9ecfb.png)

Any hint towards what the issue may be will be greatly appreciated.

So far I tried a different laptop, re-installing the plugin.
I checked exporting the presentation to HTML, which works, but the end result also looks like preview (table with ASCII art).

I'm running VS code 1.52.1
Ubuntu 20.04.
Marp 0.17.3.

Copy & paste-able table from the screenshot:

```
---
marp: true
title: Kubernetes Upgrades
theme: gaia
paginate: true
_paginate: true
---

# Kubernetes versions

Bright | Kubernetes | Initial release | Release
:-----|------|----|----|----|
8.0 | 1.6.0 | Mar 28 2017 | Mar 28 2017
8.1 | 1.10.13 | Mar 27 2018 | Feb 13 2019 | 
8.2 | 1.12.10 | Sep 28 2018 | Jul 8 2019
9.0 | 1.16.1 | Sep 18 2019 | Oct 2 2019
9.1 | 1.18.8 | Mar 25 2020 | Aug 13 2020

Omitting versions of CNI, Helm, Calico, CoreDNS, Etcd, *etc.*
```

Cheers,
Ray

**Comment by yhatt** [comment]
There is too much splitter in the delimiter row of your table.

```diff
 Bright | Kubernetes | Initial release | Release
-:-----|------|----|----|----|
+:-----|------|----|----|
 8.0 | 1.6.0 | Mar 28 2017 | Mar 28 2017
 8.1 | 1.10.13 | Mar 27 2018 | Feb 13 2019 | 
 8.2 | 1.12.10 | Sep 28 2018 | Jul 8 2019
 9.0 | 1.16.1 | Sep 18 2019 | Oct 2 2019
 9.1 | 1.18.8 | Mar 25 2020 | Aug 13 2020
```

The reason why you could see the different output between Markdown preview and Marp preview is that you're using an _outdated_ VS Code 1.52. It's using markdown-it module v10.0.0 as Markdown parser, but Marp and the latest VS Code use markdown-it v12.x.x that has included the updated and more strict table parser.

Try update your VS Code to get strict rendering.

**Comment by rayburgemeestre** [comment]
Woah, you're right, I tried updating VS Code and now it also fails to render with `marp: false`. Sorry didn't double check my markdown, I assumed it wasn't broken :dizzy_face:

**Comment by rayburgemeestre** [comment]
Thanks for the response, I guess I can close it!
