### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by yu340102** [marp-team/marp-vscode#208]
- Issue Type: `Bug`
- Extension Name: `marp-vscode`
- Extension Version: `0.17.3`
- OS Version: `Windows_NT x64 10.0.21343`
- VS Code version: `1.55.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 54473,
		"activateCallTime": 2,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "marp-team.marp-vscode",
				"_lower": "marp-team.marp-vscode"
			},
			"activationEvent": "onLanguage:markdown"
		}
	},
	"runtimeErrors": []
}
```

**Comment by yhatt** [comment]
We cannot determine the action for this issue with just the pasted info. To reopen this, let us know your expected behavior and actual behavior.

Also refer to the contribution guideline for Marp team: https://github.com/marp-team/.github/blob/master/CONTRIBUTING.md#bug-report
