### ISSUE TITLE
Cannot undock preview to other window

### ISSUE THREAD

**Issue by tobias-loew** [marp-team/marp-vscode#209]
Hi,

I really like Marp with its preview, but currently it isn't possible to put the to another window (e.g. on a second monitor) - it's always a tab in the same window as the .md source. 
The following is currently possible: After opening the preview, I can put the .md file to another window (and close the original .md). But when I type into the .md file in the new window, I do not get instant update of the preview. The preview only updates when the file is saved.

Tobias

**Comment by yhatt** [comment]
It's restriction from VS Code's editor implement and not extension specific. If VS Code cannot do this, Marp also cannot.

Instead, you should track the progress in https://github.com/microsoft/vscode/issues/10121.
