### ISSUE TITLE
Outline view : option to have the native markdown outline

### ISSUE THREAD

**Issue by eyssette** [marp-team/marp-vscode#212]
Supporting slide pages in the Outline view is sometimes great, but for long presentation, structured with markdown titles, i think it's inefficient and it would be better to have the option to go back to the native outline view in VS Code.
Thanks again for your great app!

**Comment by yhatt** [comment]
Extended outline view has provided by internal plugin `outline`. Simply adding preference to toggle it would be good.
https://github.com/marp-team/marp-vscode/blob/7be815a49b070815d01ba3d07b3355571d680ae4/src/extension.ts#L52
