### ISSUE TITLE
wanted: xyjax; enabling html and adding script doesn't work

### ISSUE THREAD

**Issue by annedranowski** [marp-team/marp-vscode#219]
How to enable https://github.com/sonoisa/XyJax-v3 please?

**Comment by yhatt** [comment]
> :warning: Please follow [our support guideline](https://github.com/marp-team/.github/blob/master/SUPPORT.md). Recommend to post at [Marp discussions](https://github.com/marp-team/marp/discussions) for asking a question about Marp and related tools/libraries.

You can't. I've already described about the reason in https://github.com/marp-team/marp/discussions/99#discussioncomment-670899.

We're not aim to support math extensions.

**Comment by annedranowski** [comment]
@yhatt what about https://katex.org/docs/autorender.html thanks
