### ISSUE TITLE
CSS is not loaded from URL which has https schema.

### ISSUE THREAD

**Issue by sonsongithub** [marp-team/marp-vscode#222]
I have tried to load a CSS theme file from github.com.
marp does not load css file from URL in `markdown.marp.themes` among `setting.json` when the URL includes "https" schema.

Thank you.

**Comment by yhatt** [comment]
> :warning: Recommend to post at [Marp discussion forum](https://github.com/marp-team/marp/discussions) for starting to ask or report.

I could not reproduce.

You are not setting URL actually represents HTML for viewing in web browser are you? Try using "Raw" URL instead.

![](https://user-images.githubusercontent.com/3993388/116815592-3c99f200-ab99-11eb-89db-9054cc627777.jpeg)

For example in [Dracula theme](https://draculatheme.com/marp):

- :x: https://github.com/dracula/marp/blob/master/dracula/dracula.css
- :heavy_check_mark: https://raw.githubusercontent.com/dracula/marp/master/dracula/dracula.css
- :heavy_check_mark: https://github.com/dracula/marp/raw/master/dracula/dracula.css

If you believed met the other error, please share the error outputted in the developer console (<kbd>Ctrl+Shift+I</kbd>).

![](https://user-images.githubusercontent.com/3993388/116815753-f85b2180-ab99-11eb-9fc8-31cfa7efcafd.png)

**Comment by sonsongithub** [comment]
>  ⚠️ Recommend to post at Marp discussion forum for starting to ask or report.

Sorry, I cannot understand the guideline...
I will confirm the reproduction conditions and post the report to the discussion board.

Thank you.
