### ISSUE TITLE
Theme does not load

### ISSUE THREAD

**Issue by Philipp0205** [marp-team/marp-vscode#241]
I setted up everything like described in the documentation but my custom theme is not applied. 

![grafik](https://user-images.githubusercontent.com/36603238/118990054-d841a580-b982-11eb-834c-5722e1fb4974.png)

Is this a bug or am I missing somehting?

**Comment by yhatt** [comment]
Do you have set the custom theme name in Markdown?

```markdown
---
marp: true
theme: custom
---

...
```

**Comment by Philipp0205** [comment]
Thanks for the fast anwer!
Yes I did, I updated the sceenshot.

**Comment by yhatt** [comment]
OK. It's just following [CSS specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity). The slide has explicitly specified `class: invert`, so it has overloaded `section` selector in the custom theme by `section.invert` definition in the default theme.

Try either of the following to fix it:

- Remove `class: invert` from Markdown (Recommended)
- Or update CSS selector `section` to `section.invert` (if you want to provide a non-invert color scheme in the custom theme)
- Or add `!important` rule to `background` declaration (⚠️ Not recommend)

**Comment by Philipp0205** [comment]
Thank you for your reply!
For some reason it does still not work after I removed `class: invert`.
Is the settings.json needed or can I remove it as well. 

![grafik](https://user-images.githubusercontent.com/36603238/119216986-6cbd1c80-bad7-11eb-9457-fe116acc3305.png)

To my understanding the heading should be red now.

**Comment by yhatt** [comment]
It looks like the custom theme is not loaded. You can check the console log whether loaded the theme in the VS Code developer tools (Help -> Toggle Developer Tools -> "Console" panel)

**Comment by Philipp0205** [comment]
I get tw errors:

**Comment by Philipp0205** [comment]
I did not put the settings in `.vsdcode/settings.json`. My bad.Thank you!

**Comment by ckaiser79** [comment]
Just an update, with VS Code 1.67.5 and when I follow yhatt's advice, the required settings are generated in the workspace file - `workspace.code-workspace` in my case. The `.vscode/settings.json` was ignored in my case as well.

Here the marp specific content of the generated file:

```json
{
  "settings": {
    "markdown.marp.chromePath": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
    "markdown.marp.enableHtml": true,
    "markdown.marp.themes": [
      "./themes/custom.css"
    ]
  }
}
```

**Comment by yhatt** [comment]
https://code.visualstudio.com/docs/editor/workspaces#_workspace-settings

> Workspace settings enable you to configure settings in the context of the workspace you have opened and always override global user settings. They are physically stored in a JSON file and **their location depends on whether you opened a folder as a workspace or you opened a `.code-workspace` file.**
