### ISSUE TITLE
Ctrl + Space auto completion key binding alternative?

### ISSUE THREAD

**Issue by fdq09eca** [marp-team/marp-vscode#242]
<kbd>Ctrl</kbd> + <kbd>Space</kbd> is my default language input key binding.

When I try <kbd>Ctrl</kbd> + <kbd>Space</kbd> for Marp auto completion in VScode, it does not do the job but switch my input language from Chinese to English. Could we customise the key binding for the auto completion? Thanks.

**Comment by yhatt** [comment]
Refer to https://code.visualstudio.com/docs/getstarted/keybindings. Change key binding for `editor.action.triggerSuggest` to prevent confliction with IME.
