### ISSUE TITLE
Why it always exports in HTML even I select PDF or PPT types?

### ISSUE THREAD

**Issue by RocStone** [marp-team/marp-vscode#247]
To reproduce the bug here is my document.
And it is always exported in HTML (but the HTML works perfectly.)

Thanks for your awesome work btw, I really really like this extension! Good Job!

_____________________________My Document_________________________________
---
marp: true
theme: gaia
footer: 'Pengqian Lu, 2021.06.07'
paginate: true
style: |
  section a {
      font-size: 30px;
  }
---

## **GMNN: Graph Markov Neural Networks**
---

# Problem to be solved
Semi-supervised object classification in relational data.

**Relational data**: Here, it's graph data.

---

# Related Field: SRL 
**Statistical relational learning (SRL)** develops statistical methods to model relational data. Generally theses methods model the dependency of object labels using conditional random fields (CRF).

---
## Brief introduction of CRF

![图 3](https://i.loli.net/2021/06/07/VyPvXTWOfes32Kx.png)  

Given a graph $G=(V,E,X,Y)$, let $V$ denotes a set of nodes, $E$ denotes a set of edges, $X$ denotes the feature matrix on nodes and $Y$ denotes the labels of nodes.

---
## Brief introduction of CRF
CRF models the conditional probability of $Y$ given $X$ as:

$p(Y|X)=\frac{1}{Z(X)}\prod_{(n_i,n_j)\in E}\psi_{i,j}(y_i,y_j,X)$

Here, $Z=\sum_Y\prod_{(n_i,n_j)\in E}\psi_{i,j}(y_i,y_j,X)$

You can define your potential functions $\psi_{i,j}$. For example, in segmentation, 

$\psi_{ij}=|y_i-y_j|(-\exp\{\frac{||z_i-z_j||}{2Mean(||z_i-z_j||_2)}\})$.

---
## Brief introduction of CRF

The limitations of SRL methods:
1. the potential functions in CRF are linear combinations of some hand-crafted feature functions. The capacity of such models is insufficient.
2. Inferring the posterior distributions of object labels for unlabeled objects remains a challenging problem.

---

## Brief introduction of GNN
![图 3](https://tkipf.github.io/graph-convolutional-networks/images/gcn_web.png)  

Learning object representations with non-linear neural architectures.

The limitations of such methods:
1. labels of objects are independently predicted on their representations. But the joint dependency of object labels is ignored.

**Comment by yhatt** [comment]
The export format actually relies the extension in the filename specified in save dialog (e.g. `slide.html`, `slide.pdf`) and _the content of slide deck does not matter_. If not detected the extension from filename, Marp will try to export into HTML with regardless of setting.

Try to set a extension `.pdf` or `.pptx` explicitly.

> Normally a corresponded extension with selected type will add automatically by VS Code, but some Linux distributions have reported won't add. Potentially related: https://github.com/marp-team/marp-vscode/issues/83

**Comment by RocStone** [comment]
> The export format actually relies the extension in the filename specified in save dialog (e.g. `slide.html`, `slide.pdf`) and _the content of slide deck does not matter_. If not detected the extension from filename, Marp will try to export into HTML with regardless of setting.
> 
> Try to set a extension `.pdf` or `.pptx` explicitly.
> 
> > Normally a corresponded extension with selected type will add automatically by VS Code, but some Linux distributions have reported won't add. Potentially related: #83

Thanks for the response, but it still doesn't work even if I explicitly set the filename as xxx.pdf.
FYI, I am using Ubuntu 20.04 with KDE theme.

**Comment by yhatt** [comment]
> How about quoted filename such as `"foobar.pptx"`?
> 
> _-- https://github.com/marp-team/marp-vscode/issues/83#issuecomment-541426564_

**Comment by yhatt** [comment]
We cannot reproduce that in Kubuntu 20.04. PDF export is working by setting `.pdf` extension explicitly.

https://user-images.githubusercontent.com/3993388/121181000-7f3ba200-c89c-11eb-8f60-c8a04647b7eb.mp4

**Comment by RocStone** [comment]
A weird thing happened, I rebooted my PC and now it works fine.
Thanks for your help!
