### ISSUE TITLE
The previewed slide page keeps jumpping when I edit the markdown document

### ISSUE THREAD

**Issue by RocStone** [marp-team/marp-vscode#248]
The previewed page will jump up when I hit the backspace key.

**Comment by yhatt** [comment]
Marp is not almost involved in preview sync so it may be a bug of VS Code. Reporting to VS Code repository would be good.

Related: https://github.com/microsoft/vscode/issues/69467

**Comment by RocStone** [comment]
After I commented all of the images and switched to the native preview of vscode, the preview doesn't jump when I was editing. 
However, when I switch to the marp preview, it jumps.

![Peek 2021-06-08 13-35](https://user-images.githubusercontent.com/13502763/121128811-9196eb00-c85e-11eb-96b3-b6789321f027.gif)

**Comment by RocStone** [comment]
This video might be even more clear
![Peek 2021-06-08 13-57](https://user-images.githubusercontent.com/13502763/121130855-8f825b80-c861-11eb-9dfe-dcbe9b688503.gif)

**Comment by yhatt** [comment]
> After I commented all of the images and switched to the native preview of vscode, the preview doesn't jump when I was editing.

Looks like still jumping slightly even in the native preview so I guess there is a root cause in VS Code, not Marp. Could you report to VS Code repository?

**Comment by yhatt** [comment]
I've made a patch in #252 but it is potentially dangerous hack and we don't want to apply if possible. I've reported details into VS Code in https://github.com/microsoft/vscode/issues/126640 so please track the progress of that.
