### ISSUE TITLE
Preview 4 times larger than it should be, on Surface Pro 200% scaled

### ISSUE THREAD

**Issue by transmixer** [marp-team/marp-vscode#249]
On my Surface Pro, the Marp preview works strangely that each slide page is **4 times larger** than it should be, see the screenshot for your reference.
![screenshot](https://user-images.githubusercontent.com/2353006/121415073-ec812d00-c999-11eb-9c00-a32bb6cc8ecc.jpg) 
Possibly related to the system scale setting - the size of text is 200%, 'cause the issue is gone when the scale is set to 100% - however, all text would be so small in this case that none is readable by human.
![SurfaceProScale](https://user-images.githubusercontent.com/2353006/121415211-0f134600-c99a-11eb-92c2-da13124c1b58.jpg)

**Comment by yhatt** [comment]
It looks like a bug clearly but I could not reproduce it in my Windows (not Surface) even if changed text scale. Could you share the context of VS Code version (Help -> About) and extension version?

If you're using the outdated VS Code / extension, #8 may be related potentially.

**Comment by yhatt** [comment]
I focused on the icon for breadcrumbs in the screenshot: you seem to use very old VS Code <= 1.36. The latest is v1.57 and Marp is only supporting >= v1.56.

Try update VS Code and extension.
