### ISSUE TITLE
Can't preview in vscode web version

### ISSUE THREAD

**Issue by nzk1912** [marp-team/marp-vscode#250]
vscode local version preview is normal~
but ~ Can't preview in vscode web version , Show whiteboard only.
How can I analyze this problem, please?

**Comment by yhatt** [comment]
I could not reproduce. Marp preview is working on VS Code for Web through GitHub Codespaces well.

![](https://user-images.githubusercontent.com/3993388/121633052-18490380-cabd-11eb-993f-03a1db2155dc.png)

Need more context to resolve this. (e.g. using browser version, OS, VS Code version, etc)

**Comment by nzk1912** [comment]
shoule use https~

![image](https://user-images.githubusercontent.com/16470935/121637807-8f31cc80-cabc-11eb-882f-22c09106aa2b.png)
