### ISSUE TITLE
Add new setting: rendering time delay

### ISSUE THREAD

**Issue by hlorand** [marp-team/marp-vscode#254]
Please add a new option to marp-vscode settings where you can specify the time delay for slide rendering after editing the document. 

For example in a Marp slideshow with 80+ slides, editing really slows down, and the text cursor sometimes freezes, because the rendering instantly triggered after 1-2 seconds of not touching the keyboard - and until the rendering is finished you can't type well. (see attached video)

It would be a good idea that the we can set how many seconds after releasing the keyboard will Marp render the slides.
Thank you

https://user-images.githubusercontent.com/6850984/122658026-e98bf680-d168-11eb-82cc-a665c0ed593f.mp4

**Comment by yhatt** [comment]
Marp cannot do that. VS Code has defined a hard-coded delay time for rendering preview (300ms), and the extension can never change it.
https://github.com/microsoft/vscode/blob/9262b186b979ca8abd1faff9bed31336e47340a6/extensions/markdown-language-features/src/features/preview.ts#L106

If you still have some freezes when disabled Marp feature by `marp: false`, it is actually the common problem of VS Code Markdown preview. Please request to [microsoft/vscode](https://github.com/microsoft/vscode) instead.

**Comment by yhatt** [comment]
Close for housekeeping.
