### ISSUE TITLE
Handle the export command while non-file schema 

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-vscode#262]
The export command assumes to save into local file (`file:///c:/xxx`). On the other hand, Marp for VS Code is also working on remote container (e.g. `vscode-remote://` schema such as Docker container, SSH, and WSL). In this case, the export command may try to save into the host filesystem `vscode-local://` which is not known by CLI if selected `Show locals` in the save dialog.

We should consider one of them:

1. Simply output error if detected non-file schema in the path for save.
2. Handle the path to the host of container (Export to a temporal file and save to the host through VS Code API)

**Comment by dwschmid** [comment]
Is this the reason why an export of e.g. c:\temp\test.md into c:\temp\test.pdf does not succeed, i.e. the exported PDF file does not show up in the selected output folder but no error message is given? Everything works if my md files are in the wsl.

If this is the case then I am forced to have the files in WSL file space, which would be inconvenient in terms of file backup with Dropbox etc.
