### ISSUE TITLE
Any thoughts on porting / testing this on Theia? 

### ISSUE THREAD

**Issue by jeremykuhnash-fauna** [marp-team/marp-vscode#28]
Theia being a cloud version of VS Code, of sorts, they now support VS Code plugins. Others I have tried seemed to work, at least in part. Thanks in advance. 

https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions

**Comment by yhatt** [comment]
An our purpose to support Marp in VS Code is not change. However, I think Theia is a interesting project.

Currently Theia's Markdown preview seems not to be able to extend by VS Code extension, but the library used to render Markdown internally is very similar to VS Code and Marp. It might be good to request adding support of VS Code's Markdown extension to Theia.

Or an extension for Theia based on [Marp Core](https://github.com/marp-team/marp-core) can create, just like [a package for Atom](https://github.com/yutaro-t/atom-marp).

**Comment by yhatt** [comment]
Note: The support of Gitpod (Theia based IDE) was added to [Marp CLI](https://github.com/marp-team/marp-cli) by contributor (marp-team/marp-cli#113). It does not a support of Theia as an extension but might useful for someone.

**Comment by mouse484** [comment]
The gitpod team will implement features that support VScode extensions.

I will talk to Gitpod team as part of the activation of Gitpod in Japan.
