### ISSUE TITLE
Compatibility with Gitpod 1.59.0

### ISSUE THREAD

**Issue by rverchere** [marp-team/marp-vscode#291]
### Version of Marp Tool

Marp VS Code 1.4.0

### Operating System

Other (fill out in the environment field)

### Environment

- OS version: Gitpod 1.59.0
- Node.js version : N/A
- VS Code version (Marp for VS Code): 1.59.0 I guess

### How to reproduce

1. Launch gitpod instance
2. Install marp extension

### Expected behavior

Marp should be installed

### Actual behavior

Marp cannot be installed:

![image](https://user-images.githubusercontent.com/232433/132586906-5bafed58-13df-475f-8455-282f6e91f8ce.png)

### Additional information

Thank you!

**Comment by yhatt** [comment]
_It's not a bug._ As shown in the latest release note, Marp for VS Code v1.4.0 requires VS Code (or compatible IDE) _1.60 and later_.
https://github.com/marp-team/marp-vscode/releases/tag/v1.4.0

Try install older version such as v1.3.0. See also: https://github.com/microsoft/vscode/issues/12764#issuecomment-442370545

**Comment by rverchere** [comment]
> 
> 
> _It's not a bug._ As shown in the latest release note, Marp for VS Code v1.4.0 requires VS Code (or compatible IDE) _1.60 and later_.
> https://github.com/marp-team/marp-vscode/releases/tag/v1.4.0
> 
> Try install older version such as v1.3.0. See also: [microsoft/vscode#12764 (comment)](https://github.com/microsoft/vscode/issues/12764#issuecomment-442370545)

Ok, thank you, sorry for the misunderstanding :/
