### ISSUE TITLE
How to create 2 columns in marp-vscode

### ISSUE THREAD

**Issue by PHHENS** [marp-team/marp-vscode#294]
Dear marp develpper,

Your software is great.
But is there any easy way to have a 2 colums layout in marp-vscode : eg picture (not bg) right and table left ?

Thanks for helping a newbie user ;-)

**Comment by yhatt** [comment]
> :warning: GitHub Issues is used for tracking the state of development. We always recommend to use [GitHub discussions](https://github.com/marp-team/marp/discussions) if you want to ask anything.

There is no better Markdown syntaxes to suit for building multi-column layout so you have always to get with the help of CSS (+ HTML). The best answer has already in https://github.com/marp-team/marpit/issues/137#issuecomment-696261979.

It is not well known, but [the 2 columns snippet for reveal.js, that is described at StackOverflow](https://stackoverflow.com/questions/30861845/how-to-use-two-column-layout-with-reveal-js), also can use in Marp without no changes.

![](https://user-images.githubusercontent.com/3993388/134173533-45bb0eb0-e160-49ea-9e76-fff1ddf8e778.png)

Don't forget to turn on HTML from the extension settings when using tags.

**Comment by PHHENS** [comment]
you may find my question stupid :
When I insert "<div> hello </div>" into vscode, it is not interpreted
by the preview, the preview shows "<div> hello </div>".
How to say this should be interpreted as HTML ?

Thanks

Le mardi 21 septembre 2021 à 05:56 -0700, Yuki Hattori a écrit :

**Comment by yhatt** [comment]
> Don't forget to turn on HTML from the extension settings when using tags.

You may have forgotten this step. Click Marp icon -> "Open Extension Settings" -> Turn on "Enable HTML".

**Comment by PHHENS** [comment]
Ok, my question was stupid ;-)
Sorry for disturbing with it.
Thanks for your help.

Le mardi 21 septembre 2021 à 06:33 -0700, Yuki Hattori a écrit :
