### ISSUE TITLE
handle yaml parse errors to user

### ISSUE THREAD

**Issue by akaguny** [marp-team/marp-vscode#320]
If user set in title or another unhandled expressions something like
* `title: Title: some expensive description` in his header
In this case we will have `Nested mappings are not allowed in compact mappings` from parser.
or
* `footer: [link address](http://localhost:8080)` in his slides dirrectives

he know nothing about parce error and about unreachable dirrectives parse (if we talk about frontMatter marp-vscode try parse all header https://github.com/marp-team/marp-vscode/blob/57d95aad81432b3af5d98c55e26be214dba808e3/src/directives/parser.ts#L67-L67 and if one of the dirrectives was failed another such as `headingDivider` does not parse anymore and dont apply to marp).

i have research this behavior - parsing is valid. It is also reproduce with standalone parse library https://runkit.com/akaguny/61c39bdd45f2720008b8831b#

 My dummy but minimum solution is add something like this (commit for this https://github.com/akaguny/marp-vscode/commit/0f9a1d44f465bdd5018b9a964da4f9fc37fb0972):
```js
      } else {
        errors.forEach((error) => {
          window.showErrorMessage(error.message)
        })
      }
```
at https://github.com/marp-team/marp-vscode/blob/57d95aad81432b3af5d98c55e26be214dba808e3/src/directives/parser.ts#L99-L99

result is messages like:
![image](https://user-images.githubusercontent.com/3505959/147167058-dc0c0316-1b48-4802-b368-a89bc4d6a21f.png)
and
![image](https://user-images.githubusercontent.com/3505959/147167089-1610d2ac-0586-4f95-85dc-0f08195c1711.png)

this is messages from parser. Good for "googling"

**Comment by yhatt** [comment]
We have no plans to fix that. An invalid state as YAML will often bring sometimes while input of directives. _Showing parse error every time while typing is not good design for users who want to focus into writing slides._ 

We have already provided a hover help about invalid YAML syntax:

![](https://user-images.githubusercontent.com/3993388/147187150-244451e3-88ea-4d54-908f-93719c05713f.png)

**Comment by akaguny** [comment]
@yhatt not for all dirrrectives. I gave spent a lot of time for find error in dirrective. When i have an error with yaml on first line another lines was ignored and render result was rediculas) . I expect 20 slides but in render got 2 and at now i also have not idea how it render ).
I can prepare some example for showing)
