### ISSUE TITLE
fragmented lists do not work well

### ISSUE THREAD

**Issue by junichiyamasaki** [marp-team/marp-vscode#327]
### Version of Marp Tool

Marp for VS Code v1.4.7

### Operating System

macOS

### Environment

- OSX 10.15.7（19H1419）
- Visual Studio Code: 1.63.2 (Universal)

### How to reproduce

```
---
marp: true
---
* test
* test2
```

### Expected behavior

Fragmented lists should appear one by one.

### Actual behavior

I do not see any animation, and it works as regular lists.

**Comment by yhatt** [comment]
Marp team could not reproduce a reported behavior by a provided Markdown example.

On the condition of the fragmented list, build animation is only available if you exported to HTML. If you exported to PDF or PPTX, the fragmented list will be rendered as a normal list. [(reference)](https://marp.app/docs/guide/fragmented-list#:~:text=Fragmented%20lists%20are%20only%20available%20if%20you%20export%20to%20HTML.%20If%20you%20export%20to%20PDF%20and%20PPTX%2C%20the%20fragmented%20list%20will%20be%20rendered%20as%20a%20normal%20list.)

If the fragmented list was not working in HTML, please confirm that JavaScript is working correctly in your browser.

**Comment by junichiyamasaki** [comment]
Thank you for the information, and I confirm that exported HTML is working well (though the preview window in VS code does not show the animation, which I misunderstood as a bug).

**Comment by yhatt** [comment]
Yes. Markdown preview has no concept of showing "one-by-one pages" so fragmented list, that depends on page navigation, cannot see in the preview.
