### ISSUE TITLE
Exported page out of bounds

### ISSUE THREAD

**Issue by Goooler** [marp-team/marp-vscode#331]
### Version of Marp Tool

@marp-team/marp-cli v1.7.0 (w/ @marp-team/marp-core v2.3.2)

### Operating System

macOS

### Environment

- OS version: macOS 12.2
- Node.js version v16.13.2
- VS Code version: 1.64.2

### How to reproduce

```md
---

## 已经调研还未实施的部分工作

#### Gradle 7.4:

- ##### [Version catalogs](https://docs.gradle.org/7.4/userguide/platforms.html)
- ##### [Type-safe project accessors](https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors)
- ##### [Configuration cache](https://docs.gradle.org/7.4/userguide/configuration_cache.html)

#### AGP 7.0+:

- ##### [R8 fullMode](https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md)
- ##### [Namespace](https://developer.android.com/studio/build/configure-app-module#set-namespace)
- ##### [nonTransitiveRClass](https://blog.blundellapps.co.uk/speed-up-your-build-non-transitive-r-files/)

#### 其他

- ##### [Hilt 2.41](https://github.com/google/dagger/releases/tag/dagger-2.41)
- ##### [Renovate](https://www.whitesourcesoftware.com/free-developer-tools/renovate/)

---
```

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/10363352/155452485-22ec8dde-0fab-4d28-af12-9af87c799ac7.png">

### Expected behavior

<img width="776" alt="image" src="https://user-images.githubusercontent.com/10363352/155451858-bd802a47-4f46-4fd7-9508-dfac753fde07.png">

### Actual behavior

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/10363352/155451627-4091a192-0b3e-4d23-9a5f-d24051ada51a.png">

**Comment by yhatt** [comment]
This is not a bug. Marp crops contents at the slide edge.

It is up to you which action to deal with it you'll take: reduce contents, split into a new slide, or make smaller font size through scoped style.

**Comment by Goooler** [comment]
But I added this:
```
<style scoped>
table { font-size: 80%; }
</style>
```
Seems it doesn't work.

**Comment by yhatt** [comment]
It's natural because `table { ... }` means to set style _only for the table_. You should use `section` (the slide container) instead of `table`.
