### ISSUE TITLE
Markdown preview doesn't update after making changes to custom theme file

### ISSUE THREAD

**Issue by frazane** [marp-team/marp-vscode#346]
### Version of Marp Tool
Marp for VS Code v1.5.1

### Operating System
Windows

###  Environment
OS version: Windows 10
VS Code version (Marp for VS Code): v1.66.2

### How to reproduce
* Create a new Markdown file with a custom theme defined in a separate local file.
* Open the preview.
* Make some changes to the custom theme (e.g. change background color) and save.

### Expected behavior
Replaces the current Markdown preview to the updated theme.

### Actual behavior
The outdated Markdown preview does not show new theme changes.

### Additional information
By reloading the window, the expected changes will apply.

![error](https://user-images.githubusercontent.com/62377868/164652054-34ec96c3-87cc-438c-8b62-08bafa5bbf71.GIF)

Might be related to #345 ?

**Comment by yhatt** [comment]
Related: marp-team/marp#288

**Comment by yhatt** [comment]
At least I could not reproduce that in my VS Code on Windows 10. Could you share a reproducible example as a repository?

![](https://user-images.githubusercontent.com/3993388/164716354-21f4788f-8dbe-43c9-8c31-4ba82842feed.gif)

**Comment by frazane** [comment]
Turns out there's a problem when locating the workspace on a NFS. I tried the same exact configuration in a workspace located on my physical machine and it worked. No idea why this happens...it would be interesting to know if others have the same issue, but my guess is that's probably not related to marp. So feel free to close the issue if you want @yhatt and thanks!
