### ISSUE TITLE
Syntax highlighting - additional languages

### ISSUE THREAD

**Issue by ewawadr** [marp-team/marp-vscode#351]
What kind of support for syntax highlighting is available in this extension? Can it be extended by user?

I would like to have support for Terraform (HCL) syntax, but it's not supported out of the box, e.g.

```terraform
terraform {
  required_providers {
    hashicups = {
      source  = "hashicorp.com/edu/hashicups-pf"
    }
  }
}
```

**Comment by yhatt** [comment]
Marp for VS Code cannot extend highlighter due to [some of security risk](https://github.com/orgs/marp-team/discussions/164#discussioncomment-1313187). Instead, you should use [Marp CLI](https://github.com/marp-team/marp-cli) to extend the engine.

```bash
npm i --save-dev @marp-team/marp-cli highlightjs/highlightjs-terraform
echo "require('highlightjs-terraform')(require('highlight.js'))" > marp.config.js
npx marp ./your-markdown.md
```

**Comment by captainabap** [comment]
I tried the above solution but it works only localy with the marp-cli.
When I use Github Actions it fails and the error message is: 

`[ ERROR ] Could not find or parse configuration file. [./marp.config.js]`

Do you have an idea what could be wrong?

**Comment by yhatt** [comment]
Try running `node marp.config.js` before running Marp CLI and confirm that it does not throw any kind of error. If the error was thrown, you may have wrong setup about depending Node.js modules.

```yaml
steps:
  - run: |
      npm i --save-dev @marp-team/marp-cli highlightjs/highlightjs-terraform
      echo "require('highlightjs-terraform')(require('highlight.js'))" > marp.config.js
      node marp.config.js
      npx marp ./your-markdown.md
```

**Comment by captainabap** [comment]
This helped a lot! Now the formatting is working very well with a custom language. 
Your support is excellent and very much appreciated!
