### ISSUE TITLE
Absolute path for common resources 

### ISSUE THREAD

**Issue by JamesLarkinWhite** [marp-team/marp-vscode#354]
In a Presentation, we will usually have some common resources, like common backbground images etc. Absolute pathes do not work in vscode due to security reasons if i understand it correctly

https://github.com/marp-team/marp-vscode/issues/68

Is there any other way to solve this issue in marp for vscode? I have read somewhere that you could use the keyworkd marp: and use references from the installation path of marp? 

I have all my notetaking/slides etc in one vscode workspace. Is it somehow possible to reference my common resources from tht workspace root or can i register my folder with common images in a different way for use with marp?

If so, could you give me an example showing the snytax?

Thank you in adance

**Comment by yhatt** [comment]
There is a loophole to use raw `<img>` tag instead of `![]()` Markdown syntax, by enabling HTML tags from the extension settings.

```html
<img src="/Users/username/Documents/your-workspace/image.png" />
```

In current VS Code version, an `<img>` tag with absolute path seems to be able to preview and export correctly if that path pointed locating in the current workspace.

**Comment by JamesLarkinWhite** [comment]
> There is a loophole to use raw `<img>` tag instead of `![]()` Markdown syntax, by enabling HTML tags from the extension settings.
> 
> ```
> <img src="/Users/username/Documents/your-workspace/image.png" />
> ```
> 
> In current VS Code version, an `<img>` tag with absolute path seems to be able to preview and export correctly if that path pointed locating in the current workspace.

At least in my case it doesn´t seem to work. I do not have the image files in the main folder, where my workspace.json file is located.

I do have the path to the main folder of the image files added in this json file like:

"folders": [
		{
			"path": "path/to/folder",
			"name": "Images"
		}
]


The image files are than located in subfolders like this: `folder/title-images` and `folder/Agenda-iamges` and so on.


It would be really nice if this could be possible. Otherwise creating slides will always just be possible from one location. This gets messy fast, at least for me.

Thank you for takingt the time!

**Comment by yhatt** [comment]
It is a design of VS Code workspace with deeply considered about security, and I think there is no correct way to access resources located at the `image` workspace from Markdown that belongs to other workspace. It would be difficult that a mere Markdown preview add-ons influence the fundamental design of VS Code.

You should track a related issue at VS Code repository: https://github.com/microsoft/vscode/issues/114319

Alternatively you can use [Marp CLI's preview mode](https://github.com/marp-team/marp-cli#preview-window---preview---p) that has not a concept of workspace. (Refer resources from absolute path w/ using `--allow-local-files` option)
