### ISSUE TITLE
Show mermaid diagrams in the exported file

### ISSUE THREAD

**Issue by niosus** [marp-team/marp-vscode#376]
### Version of Marp Tool

Marp for VS Code v2.2.1

### Operating System

macOS

### Environment

- OS version: macOS Monterey 12.4
- VS Code version (Marp for VS Code): VS Code 1.70

### How to reproduce

Just create a simple "presentation" with mermaid `div`. This renders correctly in VSCode but when exported is not rendered. I might be missing something for sure but I would love to have a way to get it rendered at least in the HTML output from Marp.

Here is an example "presentation"

```
---
marp: true
---

<div class="mermaid">
flowchart LR
    A -->|Yes| B
    A -->|No| C
</div>
```

### Expected behavior

The diagram should be rendered in the exported output from Marp

### Actual behavior

The diagram is represented as jumbled text.

### Additional information

Feel free to ask me anything if I can be of any help.

**Comment by yhatt** [comment]
- https://github.com/marp-team/marp-core/issues/139
- https://github.com/yhatt/marp/issues/125#issuecomment-509485121

**Comment by niosus** [comment]
Thanks and sorry for the noise! I missed those discussions!
