### ISSUE TITLE
LaTeX/KaTeX rendering issue for PDF exports only

### ISSUE THREAD

**Issue by lettersforword365** [marp-team/marp-vscode#393]
I was testing out Marp and tried some LaTeX code for mathematical formulae.

I found that sigma notation does not seem to render correctly in PDF exports:

**PDF Export**:
![image](https://user-images.githubusercontent.com/98777122/209449567-f4dbf084-047e-421a-8a4e-ceebeda2f2ed.png)

**HTML/PPTX Export**:
![image](https://user-images.githubusercontent.com/98777122/209449575-3553ef3b-ead5-4c62-94df-86d72ce16a42.png)

I am running Marp for VS Code v1.5.2 on VS Code 1.70.1; device is on Windows 11 22H2.
The code for the formula I am using is:

```latex
# Some $\LaTeX$ Code

<br>

$$
\sum_{k=1}^{n}k^2 = \frac{n(n+1)(2n+1)}{6}
$$
```

This appears to be the case when I have not declared the math typesetting, or if it is declared as `katex`.

This is not the case when math typesetting is declared as `mathjax`, which is odd, as [this](https://github.com/marp-team/marp-core#math-global-directive) says `mathjax` is used in rendering if there is no declaration (there is also a stylistic difference in rendering; no declaration appears to be using katex.)

**PDF using MathJax**:
![image](https://user-images.githubusercontent.com/98777122/209449582-653186bd-aa46-4f6e-ad28-809ce42562df.png)

I prefer usage of katex. Is there any "quick fix" for this, or a way in which different rendering engines could be used for different parts of the same equation?

**Comment by yhatt** [comment]
It seems to reproduce only in Chrome if exported to HTML. Firefox and Safari does not reproduce. (Marp's PDF export is depending on Chrome)

Marp has applied [auto-shrink the size to KaTeX block](https://github.com/marp-team/marp-core#auto-shrink-the-block), and it may be a one of incompatible parts with the auto scaling feature, as same as marp-team/marp-core#159 and marp-team/marp-core#236.

### Workaround

Add following global style in Markdown.

```css
<style>
  .katex .delimcenter,
  .katex .op-symbol {
    display: inline-block;
  }
</style>
```

If this workaround is working well, going to consider to add into [KaTeX default style by Marp Core](https://github.com/marp-team/marp-core/blob/main/src/math/katex.scss).

**Comment by yhatt** [comment]
> This appears to be the case when I have not declared the math typesetting, or if it is declared as katex.
>
> This is not the case when math typesetting is declared as mathjax, which is odd, as [this](https://github.com/marp-team/marp-core#math-global-directive) says mathjax is used in rendering if there is no declaration (there is also a stylistic difference in rendering; no declaration appears to be using katex.)

In Marp for VS Code, use the library _preferred in the extension settings_ if not defined `math` directive. You says "I prefer usage of katex" so you may be setting `markdown.marp.mathTypesetting` as `katex`. In this case, it's expected behavior that uses KaTeX when there is not set math directive.

**Comment by lettersforword365** [comment]
> you may be setting `markdown.marp.mathTypesetting` as `katex`

just had a look at extension settings; looks like that is the default.

the workaround seems to work well for me as well; thanks for that!
