### ISSUE TITLE
duplicated thumbnails are displayed and float:flex does not work

### ISSUE THREAD

**Issue by GXY2017** [marp-team/marp-vscode#398]
### Version of Marp Tool

marp for vs code

### Operating System

Windows

### Environment

Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

### How to reproduce

````
<div id="thumbnails-container">
    <img id="thumbnail1" src="starter.jpg" class="thumbnail">
    <img id="thumbnail2" src="ending.jpg" class="thumbnail">
</div>

<style scoped>
    .thumbnail {
        width: 200px;
        height: 200px;
        float: right;
        display: flex;
        flex-wrap: wrap;
    }

    .thumbnail:hover {
        width: 1500px;
        height: 500px;
    }
</style>

````

### Expected behavior

1.  I expect to see 2 thumbnails,
2. I expect the thumbnails to be vertically displayed.

### Actual behavior

 but it displays 3 thumbnails and horizontally.

**Comment by yhatt** [comment]
It looks like you are asking about a general CSS problem. marp-vscode issue tracker is only for tracking issues related to the behaviour of the Marp extension.

Consider asking on the [Marp discussion forum](https://github.com/orgs/marp-team/discussions) or [StackOverflow](https://stackoverflow.com/). The latter is likely to have many CSS experts.
https://github.com/marp-team/.github/blob/master/SUPPORT.md#question

---

> I expect to see 2 thumbnails,

Yes, I also only see 2 thumbnails when I view Markdown you described, and _never see 3 thumbnails_.

> I expect the thumbnails to be vertically displayed.

`float: right;` is meaning to allow wrapping by inline elements (including other images) around it, _not meaning aligning images to the right_. The first thumbnail has allowed wrapping by other elements, so the second thumbnail places just next to the first.

To align images to right, normally you have to display the parent element as flex container. Define `flex-direction: column` to display images vertically, and `align-items: flex-end;` to align to the right.

```html
<style scoped>
    #thumbnails-container {
        display: flex;
        flex-direction: column;
        align-items: flex-end;
    }

    .thumbnail {
        width: 200px;
        height: 200px;
    }

    .thumbnail:hover {
        width: 1500px;
        height: 500px;
    }
</style>
```

**Comment by GXY2017** [comment]
Thank you for your prompt solution.  I will ask on StackOverflow.
