### ISSUE TITLE
Marp CLI integration to export PDF

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-vscode#4]
VSCode has several extensions to export PDF, e.g. [Markdown PDF](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf). However, these cannot use the Marp extension to convert.

We are planning to add [Marp CLI](https://github.com/marp-team/marp-cli) integration for exporting PDF, HTML, and images. By this integration, VSCode extension would be able to replace/exceed [the old Marp writer](https://github.com/yhatt/marp).

**Comment by iroychoudhury** [comment]
Is it possible to have the `--html` option to be`true` by default in the Marp VSCode viewer? Currently there is no option to pass this option to the VS code extension. I wonder if we can make this part of the frontmatter in a .md file.

Thanks!

**Comment by yhatt** [comment]
I think it should toggle HTML option in extension's setting. Marp Next is thinking user security first. If `--html` is enabled by default, the unexpected JS execution would be allowed.

It's off-topic in this issue, so we will create another issue to support HTML setting.

**Comment by yhatt** [comment]
*For reacted users*: In the latest version (v0.3.2) has a command to export slide deck to PDF, HTML, and so on. (<kbd>Ctrl/Cmd+Shift+P</kbd> 👉 Select "Marp: Export slide deck...")

![](https://user-images.githubusercontent.com/3993388/57524554-1d2dad00-7363-11e9-9389-afa51434a52c.gif)

Enjoy writing deck!

**Comment by eric-burel** [comment]
Hi, I end up with this Error when running the export using VS Code? 
```
Failure to export. Marp CLI throwed unexpected error with exit code 1.
```
Any idea how I could get a more precise error message?
I run VS code 1.39.2 on Ubuntu 18
The rendering is otherwise fine in VS code, including using a custom theme.
