### ISSUE TITLE
About Merging Preview to the Marp Shortcut Button

### ISSUE THREAD

**Issue by julynncc** [marp-team/marp-vscode#400]
I think it would be more convenient to separate the preview function of Marp from the default preview function of VSCode and move the preview button to the shortcut button of Marp. I don't know whether there is such a development plan.

**Comment by yhatt** [comment]
Marp for VS Code has been designed to enhance the built-in Markdown preview.

A separated Marp view is required custom WebView, and we have thought that brings development unnecessary complexity and low maintainability. We would not do it if we could not achieve the Marp extension long live.
