### ISSUE TITLE
About rendering Mermaid code to generate images

### ISSUE THREAD

**Issue by julynncc** [marp-team/marp-vscode#401]
I often use the Mermaid drawing engine when writing Markdown files, but currently the Marp preview does not support rendering Mermaid. Would you like to develop such functions?

**Comment by yhatt** [comment]
Duplicated: marp-team/marp#207, marp-team/marp-core#139

We have no plans to implement mermaid support as default because of reliability and simplicity of Marp ecosystem. It should always be a Marp plugin.
