### ISSUE TITLE
preview does not behave well with sticky scroll

### ISSUE THREAD

**Issue by cyril-marpaud** [marp-team/marp-vscode#419]
### Version of Marp Tool

Marp for VS Code 2.6.0

### Operating System

Linux

### Environment

- OS version:Ubuntu 22.04
- <strike> Node.js version (Marpit / Marp Core/ Marp CLI): [e.g. Node.js 14.17.1]</strike>
- VS Code version (Marp for VS Code): VS Code 1.78.2

### How to reproduce

1. enable sticky scroll in VSCode settings: `"editor.stickyScroll.enabled": true,`
2. open a slide deck (`.md` file) and its preview side by side
3. vertical sync struggles (particularly when the source markdown spans over many lines)

### Expected behavior

the preview pane stays in vertical sync with the source markdown pane (the preview "start point" should be the first non sticky line)

### Actual behavior

the preview pane does not stay in vertical sync with the source markdown pane (the preview "start point" actually seems to be the first displayed line, meaning the first sticky line)

**Comment by yhatt** [comment]
VS Code seems to have treated sticky headers as floating contents that are not affected by scroll sync. The same problem can also be seen when Marp preview was disabled. _So this is a VS Code issue, not a Marp issue._

Marp for VS Code extension cannot change VS Code's scroll sync logic, so there is nothing more we can do.

You should report this in the VS Code issue tracker instead.
https://github.com/microsoft/vscode/issues
