### ISSUE TITLE
Add support for `lang` directive

### ISSUE THREAD

**Issue by ludelafo** [marp-team/marp-vscode#430]
Hi Marp team!

I'm interested to use the [hyphens](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens) CSS property as follow:

```yaml
theme: gaia
style: |
    p {
        hyphens: auto;
    }
```

In order for this to work, I need to set the [lang](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) attribute.

`marp-cli` defines the argument `lang` in its [options](https://github.com/marp-team/marp-cli#options). When using the command-line tool as `npx @marp-team/marp-cli@latest --lang en --pdf --output README.pdf README.md`, the hyphens are correctly rendered.

I would like to add support for the `lang` directive in `marp-vscode` so the language of the document can be set:

```yaml
theme: gaia
lang: en
style: |
    p {
        hyphens: auto;
    }
```

From my understanding of the codebase, the starting point would be https://github.com/marp-team/marp-vscode/blob/d9af184ed12b65bb28c0f328e250955d548ac1d1/src/directives/definitions.ts by adding a new directive such as:

```ts
  // Marp CLI metadata options
  createDirectiveInfo({
    name: 'lang',
    description: 'Set lang of the slide deck.',
    allowed: directiveAlwaysAllowed,
    providedBy: DirectiveProvidedBy.MarpCLI,
    type: DirectiveType.Global,
    details: 'https://github.com/marp-team/marp-cli#metadata', // Need to update the metadata as well
  }),
```

Would this feature be useful for `marp-vscode`? I would be glad to implement this feature if you are interested.

**Comment by yhatt** [comment]
If so, the starting point would be Marp CLI rather than Marp for VS Code. Could you create an Issue in the Marp CLI repository to propose implementing `lang` global directive?

**Comment by ludelafo** [comment]
Thank you very much @yhatt!
