### ISSUE TITLE
No popup when exporting slide deck

### ISSUE THREAD

**Issue by Xav-Pe** [marp-team/marp-vscode#432]
Hello,

When exporting from the command palette or the quick pick menu , I have no pop-up like this one :

![image](https://github.com/marp-team/marp-vscode/assets/40688444/2b6f3bc5-fefe-460e-afd6-8d25c688280b)

VSCode just asks me where to save the file with the extension defined in the ``markdown.marp.exportType`` setting.

I'm on Windows 10, up to date VSCode and 2.7.0 (latest) version of VSCode Marp. I'm not sure if there's a setting about it or if this popup is supposed to work only on MacOS.

Thanks!

**Comment by yhatt** [comment]
> VSCode just asks me where to save the file with the extension defined in the markdown.marp.exportType setting.

It's expected behavior. This screenshot shows the file saving dialog in macOS. So that popup is just same meaning as the file save dialog that you have seen in Windows :)

**Comment by Xav-Pe** [comment]
Ow, now it's obvious I never touched MacOS 😬 

Thanks for your work and your answer!
