### ISSUE TITLE
Not working, even though I have chrome.exe on my path

### ISSUE THREAD

**Issue by Bios-Marcel** [marp-team/marp-vscode#44]
I can't export the presentation, even though chrome.exe is on my path. There is no concise error either, it just claims I don't have chrome.

**Comment by yhatt** [comment]
We will find out the installed Chrome based on [chrome-launcher](https://github.com/GoogleChrome/chrome-launcher). Where is the located `chrome.exe` in full path?

**Comment by Bios-Marcel** [comment]
Well, maybe it doesn't work because I am using *Ungoogled Chrome*.

Anyway, it should at least allow passing a custom chrome executable or so, I think.

Here lies the executable:

`C:\Users\msc\scoop\apps\ungoogled-chromium\current\chrome.exe`

Which is also on the `PATH` Variable in Windows.

**Comment by yhatt** [comment]
Oh, I see. We will try to add the extension preference to set custom chrome path.

I think `CHROME_PATH` environment value may have already recognized while exporting. As a workaround, try below commands in `cmd.exe`

```
set CHROME_PATH=C:\Users\msc\scoop\apps\ungoogled-chromium\current\chrome.exe
code
```

**Comment by yhatt** [comment]
The custom Chrome path preference was added by merging #46. We are going to ship out the bumped version in shortly.
