### ISSUE TITLE
Can't using Html label <sup> in Marp for VS code 

### ISSUE THREAD

**Issue by imllt-l** [marp-team/marp-vscode#442]
### Version of Marp Tool

Marp for VS Code v2.7.0

### Operating System

macOS

### Environment

- OS version: [e.g. Windows 10 / macOS Big Sur 11.4 / Ubuntu 20.04.2]
- Node.js version (Marpit / Marp Core/ Marp CLI): [e.g. Node.js 14.17.1]
- VS Code version (Marp for VS Code): [e.g. VS Code 1.57.1]

### How to reproduce

To enable HTML in the vs code settings and use the <sup></sup> label  after the slide not presented the footnote ,it only have a blank in the silde view

### Expected behavior

have a footnote before the text 
<img width="877" alt="image" src="https://github.com/marp-team/marp-vscode/assets/29442948/9f5c404a-2fb6-4246-8975-623a0e382f2e">

### Actual behavior

 only have a blank in the silde view
<img width="865" alt="image" src="https://github.com/marp-team/marp-vscode/assets/29442948/02db54f8-35c3-4662-b584-864cd84d8de4">

**Comment by yhatt** [comment]
This issue could be simplified to that inline elements with `position: relative` not showing up in VS Code's Marp preview. 

```markdown
---
marp: true
---

# Hello, <span style="position: relative;">world</span>!
```

![](https://github.com/marp-team/marp-vscode/assets/3993388/ccdd4d28-558a-4596-afbe-749572250972)
