### ISSUE TITLE
Failure to export: [CLIError] Failed converting Markdown. (spawn UNKNOWN)

### ISSUE THREAD

**Issue by song-wensong** [marp-team/marp-vscode#450]
Marp for VS Code v2.8.0
Windows 10
When I `Export Slide Deck...`
It reports the error:
`Failure to export: [CLIError] Failed converting Markdown. (spawn UNKNOWN)`

I don't know why and how to fix it.

**Comment by yhatt** [comment]
Duplicated: #439

**Comment by song-wensong** [comment]
> Duplicated: #439

If I use AdBlock in edge extension, then I can't Export Slide Deck...?

**Comment by yhatt** [comment]
The error `spawn UNKNOWN` is generally known to occur when the current user does not have the necessary permissions to spawn the browser process.

That is often due to restrictions by Windows group policies. It is not related to the browser's extensions such as the adblocker.

**Comment by song-wensong** [comment]
> The error `spawn UNKNOWN` is generally known to occur when the current user does not have the necessary permissions to spawn the browser process.
> 
> That is often due to restrictions by Windows group policies. It is not related to the browser's extensions such as the adblocker.

Thank you!
So how could I set it up to have the necessary permissions to spawn the browser process?

**Comment by yhatt** [comment]
I cannot provide a specific because generally these kinds of restrictions are set by system administrators. Please consider to review with your IT department or system administrator.

**Comment by song-wensong** [comment]
> I cannot provide a specific because generally these kinds of restrictions are set by system administrators. Please consider to review with your IT department or system administrator.

Thank you!
