### ISSUE TITLE
CSS theme files matching does not support wildcards

### ISSUE THREAD

**Issue by Daucloud** [marp-team/marp-vscode#454]
I want to use several custom themes, and I found that I couldn't use wildcards like `"./examples/*.css", but "./examples/test.css" would work. Usually the `settings.json` supports the wildcards. Is this some question `markdown.marp.themes` have itself?

**Comment by yhatt** [comment]
The `marp.markdown.themes` setting in Marp for VS Code has exactly compatible rule with [`markdown.styles` setting for VS Code's Markdown preview](https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css).

`markdown.styles` does not support glob pattern such as `./example/*.css`, so `marp.markdown.themes` does not support it too. There are no plans to support globs in Marp as long as VS Code does not.
