### ISSUE TITLE
Local image not exported to HTML when opened on another computer

### ISSUE THREAD

**Issue by warpedwood** [marp-team/marp-vscode#461]
Ubuntu 24.04
VS Code 1.93.0 (snap)
Extension version 2.8.0
Brave 1.69.162 (deb)

When I export remote and local images, saved in the same folder as the presentation, to HTML, all the images are exported. However, when I open the HTML file on another computer, the local image does not appear. When exported in PDF format, the local image is visible. 

I tried the solutions proposed in a related issue, but it didn't work #416

**Comment by yhatt** [comment]
Unlike PDF and other formats, the exported HTML does not include image resources. If you moved only HTML into another computer, you should move other resources too.
