### ISSUE TITLE
Currently, the Marp plugin does not support the Mermaid syntax in Markdown, which prevents the direct generation of images using Markdown.

### ISSUE THREAD

**Issue by aiyinluya** [marp-team/marp-vscode#469]
The current plugin screenshot is as follows:
![](https://s2.loli.net/2024/11/14/ZVALYyFnHuj69XD.png)

The correct image display is as follows:
![](https://s2.loli.net/2024/11/14/3rbkIJlBPDdsqG1.png)

**Comment by yhatt** [comment]
> [!NOTE]
> Thanks for creating a issue. However, we would appreciate your help in writing in English for the discoverability and workability of Marp team and our community.

**Comment by aiyinluya** [comment]
I have already modified the question.

**Comment by aiyinluya** [comment]
> Note
> 
> Thanks for creating a issue. However, we would appreciate your help in writing in English for the discoverability and workability of Marp team and our community.

I have already modified the question.

**Comment by yhatt** [comment]
Marp has no support for mermaid.js officially due to technical lacked rendering reliability (marp-team/marp-core#139). Check out related/duplicated issues and discussions:

- marp-team/marp#207
- #191 
- #376 
- #401

Some described workarounds by community might help you.
