### ISSUE TITLE
More img usage example

### ISSUE THREAD

**Issue by qqhann** [marp-team/marp-vscode#47]
Hello, 
I've been using Marp desktop (deprecated) and I love it.
I recently found out there is Marp Next project and VSCode extension.

The problem I have is the image usage is different from Marp desktop and VSCode version.
Could you provide more examples on how to add image?

**Comment by qqhann** [comment]
https://github.com/marp-team/marpit/issues/141

I barely found these examples such as `[h:340]`, but it is not clear where you can find full example usages.

**Comment by yhatt** [comment]
The conversion engine for all of Marp Next tools are based on [Marpit framework](https://github.com/marp-team/marpit). See the document of Marpit.
https://marpit.marp.app/image-syntax
