### ISSUE TITLE
Bump @marp-team/marp-core from 3.9.0 to 4.0

### ISSUE THREAD

**Issue by alanlivio** [marp-team/marp-vscode#470]
This issue only asks to marp-vscode bump version of @marp-team/marp-core from 3.9.0 to 4.0 [@​marp-team/marp-core's releases](https://github.com/marp-team/marp-core/releases).

**Comment by yhatt** [comment]
It's in progress at #462. The blocker for bumping version is that an audit for vulnerability check is failing. I'm going to work for that in this year, but currently I'm busy for my other projects. We are welcome to a pull request to fix audit on depending libraries from contributors.
