### ISSUE TITLE
size global directive failed in vs code extension 0.8.0

### ISSUE THREAD

**Issue by fabulist-ssdd** [marp-team/marp-vscode#61]
Hi, I have tried out new feature for customized css in 0.8.0. It works fine. However, it seems that the size global directive 4:3 has been somehow deactivated. The only size that worked is 16:9, if I use the `size: 4:3`, the preview won't change. The exported pdf is fine for 4:3 though. 

<img width="1552" alt="20190801-marp-issue" src="https://user-images.githubusercontent.com/50709309/62279376-89104500-b47c-11e9-996a-5a90792e9814.png">

I couldn't confirm whether this is an individual case which is just for my end, or ... any way, I am also using the marp web app installed from chrome, the size directive is ok in there. 

Looking forward to your reply, THX.

**Comment by yhatt** [comment]
Hmm, certainly `size` global directive seems not to work. It reproduces in a very simple Markdown too.

```markdown
---
marp: true
size: 16:9
---
```

marp-vscode v0.8.0 has added [an internal plugin](https://github.com/marp-team/marp-vscode/blob/master/src/plugins/custom-theme.ts) to extend Marp for using custom CSS, but it raises error when using `size`. 

<img width="1230" src="https://user-images.githubusercontent.com/3993388/62281374-a3502000-b488-11e9-9626-84cfa8fccf22.png">

**Comment by yhatt** [comment]
It was fixed in v0.8.1. Please update the extension. Sorry for a while of inconvenience.

**Comment by fabulist-ssdd** [comment]
> It was fixed in v0.8.1. Please update the extension. Sorry for a while of inconvenience.

thanx. it works now.
