### ISSUE TITLE
local images

### ISSUE THREAD

**Issue by pnizet** [marp-team/marp-vscode#68]
the syntax 
`![bg](C:\Users\me\Pictures\slide.png)`

doesn't seems to work. It was previously working on https://github.com/yhatt/marp 
Did I miss something about the syntax ?

thanks

**Comment by yhatt** [comment]
Transferred issue from Marpit framework :arrow_forward: Marp for VS Code. 🚚 

In regular VS Code, rendering local image files that there are in the out of current workspace have restricted in preview pane for security. (`vscode-resource)

![](https://user-images.githubusercontent.com/3993388/64190061-8015f780-ceb0-11e9-863f-592f5b13531f.png)

You have to place images on same workspace.

**Comment by pnizet** [comment]
ok thanks 👍
