### ISSUE TITLE
Page Number not shown

### ISSUE THREAD

**Issue by lizhewen** [marp-team/marp-vscode#69]
I'm using the VSCode plugin of Marp and when I insert `<!-- page_number: true -->` at the beginning of my slide, no page number is shown at bottom-right corner. Other features work fine such as `size`, `theme`, and `footer`.

**Comment by yhatt** [comment]
Perhaps you may be watching a document for *the outdated Marp app*.

In Marp Next tools, `page_number` directive was renamed to `paginate`. So you have to use `<!-- paginate: true -->` instead.
https://marp.app/blog/the-story-of-marp-next#directives

**Comment by lizhewen** [comment]
Thank you! This really helps.
