### ISSUE TITLE
rendering differences between the VS code integration and the Mac tool

### ISSUE THREAD

**Issue by sgandon** [marp-team/marp-vscode#7]
when rendering my markdown document in VSCode I get different rendering than in the Mac desktop client (0.0.14)
here is a screen shot of the diff:
https://github.com/sgandon/Git-sandbox/blob/master/Capture%20d%E2%80%99%C3%A9cran%202019-02-21%20%C3%A0%2016.00.21.png

**Comment by yhatt** [comment]
Marp VSCode is based on brand-new [<img src="https://web.marp.app/favicon.ico" width="16" height="16" /> Marp](https://marp.app/) ecosystem (as known as Marp Next), and NOT [<img src="https://raw.githubusercontent.com/yhatt/marp/master/images/marp.png" width="16" height="16" /> the old Marp](https://yhatt.github.io/marp/) desktop application. 

Your deck needs migration to suit to Marp Next if you want to preview in VSCode. There is a bit losing compatibility from Marp desktop app.

We have the documentation of [Marpit Markdown](https://marpit.marp.app/markdown) (syntax from the new framework) and [the features of Gaia theme](https://github.com/marp-team/marp-core/tree/master/themes#gaia).

**Comment by yhatt** [comment]
I guess from your screenshot to need to change these directives...

- `<!-- page_number: true -->` -> `<!-- paginate: true -->` (`page_number` -> `paginate`)
- `<!-- template: gaia -->` -> `<!-- class: gaia -->` (`template` -> `class`)
- `<!-- *template: gaia -->` -> `<!-- _class: gaia -->` (`*` -> `_`)

**Comment by sgandon** [comment]
Ok thanks a lot. 
I don't mind at all switching to the Marp Next but is there a simple way to export to pdf ?

**Comment by yhatt** [comment]
Currently you can use [Marp CLI](https://github.com/marp-team/marp-cli).

```bash
# Run below in terminal after installing Node.js
npx @marp-team/marp-cli slide-deck.md -o output.pdf
```

Marp VSCode will implement PDF export via Marp CLI in #4.
