### ISSUE TITLE
Long line goes out of screen

### ISSUE THREAD

**Issue by taianguo** [marp-team/marp-vscode#76]
When I enter a long linux path to the markdown file, the line displayed in marp goes beyond the screen, how to solve the problem? The problem can be seen [here](https://ibb.co/LpK81f7)
This is my configurations in the head of the markdown file:
```
marp: true
theme: uncover
paginate: true
_paginate: false
```
Thank you so much!

**Comment by yhatt** [comment]
You can tweak style to set [`word-break` css property](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) as `break-word` or `break-all`. Marp default theme has`word-break: break-word;` definition but it seems not to be defined in others.

Try to add `<style>` tag like this:

```markdown
---
marp: true
theme: uncover
---

<style>
section {
  word-wrap: break-word;
}
</style>

/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx
```

<img src="https://user-images.githubusercontent.com/3993388/65046122-f3ccff80-d99a-11e9-8086-4c287d1f9176.png" width="300" />

**Comment by taianguo** [comment]
It worked! Thank you so much! @yhatt

**Comment by yhatt** [comment]
@taianguo My pleasure. You may contribute for adding CSS declaration to our built-in themes if you have interested. https://github.com/marp-team/marp-core/issues/108
