### ISSUE TITLE
preview of slides do not scale properly on linux

### ISSUE THREAD

**Issue by tosaba** [marp-team/marp-vscode#8]
having marp-cli integrated into vscode is really great, I just noticed that in the latest version, the slides do not scale properly in the preview panel

Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

![image](https://user-images.githubusercontent.com/17127576/53197504-abbf4780-361a-11e9-8fb8-e8138bb1a6b1.png)

**Comment by yhatt** [comment]
I have never seen this scene in Windows and macOS. I'm going to start testing in Linux. Would you have a minimum Markdown to reproduce this?

I had battled against the scaling bug in last year. (https://github.com/marp-team/marpit/pull/35, https://github.com/marp-team/marp-cli/pull/15) VSCode uses the old Chromium 66, and it revives me an old headache. 😣

**Comment by tosaba** [comment]
Here is the minimum example. I also tested it with all my markdown related extensions being deactivated, but they don't interfere (except  _markdown all in one_ [#9](https://github.com/marp-team/marp-vscode/issues/9))

```markdown
---
marp: true
---

# header

- bullet point contents
- bullet point contents
- bullet point contents

---
```



![image](https://user-images.githubusercontent.com/17127576/53266580-7c274280-36e1-11e9-8845-f1dba2e1e88c.png)

**Comment by yhatt** [comment]
I've tested provided Markdown in VSCode 1.31.1 and ubuntu 18.10, but it did not reproduce.

![screenshot from 2019-02-24 00-03-13](https://user-images.githubusercontent.com/3993388/53288141-28435900-37c8-11e9-92a8-662d3a88c869.png)

**Comment by yhatt** [comment]
The other probable case to interfere is custom CSS style. Would you have any CSS file defined in `markdown.styles` preference?

**Comment by tosaba** [comment]
For me, it appears with default options and disabled extensions (v. 1.31.1 , ubuntu 18.04). I also didn't link any css stylesheets. I tested this on two separate computers with different graphics cards.

I also started vscode from the command line with `--disable-gpu`, but there is no difference.

**Comment by yhatt** [comment]
I had tried to reproduce again in ubuntu 18.04.1 LTS, but it works correctly.

We added `help wanted` tag. PR is welcome if anyone resolves this.

**Comment by yhatt** [comment]
My co-worker has reported a reproducible setting: `"window.zoomLevel": 1`.

![zoom](https://user-images.githubusercontent.com/3993388/54654321-1fad1c80-4b01-11e9-88d8-64e3fc6cf632.gif)

@tosaba Could you confirm to show slide with correct scaling by resetting zoom level?

**Comment by tosaba** [comment]
:+1+ I confirm that this causes the issue in my case

**Comment by yhatt** [comment]
Done. An updated v0.1.0 has a workaround for zoom level. Previewed slide would have correct scales.
