### ISSUE TITLE
VSCode 1.38.1 - Cannot export my Markdown (unless in HTML)

### ISSUE THREAD

**Issue by pcotret** [marp-team/marp-vscode#80]
Hi,
I'm working with Visual Studio Code 1.38.1 and I'm getting an error message when I want to export to PDF/PNG/JPG (HTML export works!).

![error](https://user-images.githubusercontent.com/404135/65754289-02d94d80-e111-11e9-8cb6-d8ac7f050781.png)

Any idea?

**Comment by yhatt** [comment]
Would you provide us error logs? After executing export, Marp CLI will be outputted error logs in VS Code developer console. (Help -> Toggle Developer Tools -> `Console` tab)

**Comment by pcotret** [comment]
My bad, the environment variable for Chromium wasn't set.
Everything works now :)

**Comment by yhatt** [comment]
All right. Or you can set custom chrome path from preference `markdown.marp.chromePath`. 👌 

@pcotret Please let me ask extra question for clearify what is happened. Are you using macOS or Windows? (Marp CLI will be supposed to detect Chromium automatically if you are using Linux)
