### ISSUE TITLE
Can't preview with Ctrl + K V & Ctrl + Shift + V if other markdown viewers are installed

### ISSUE THREAD

**Issue by tats-u** [marp-team/marp-vscode#82]
Markdown viewers like https://github.com/shd101wyy/markdown-preview-enhanced replacing the default viewer also take over keyboard shortcuts Ctrl+K V & Ctrl+Shift+V, which is used for opening them.  3rd-party viewers prevents us from previewing slides using the default viewer and this extension.

To reproduction:
1. Install this extension and Markdown Preview Enhanced.
2. Create new slide written Marp-flavored Markdown
3. Preview by pressing Ctrl+K V
4. Markdown Preview Enhanced appears and slide preview doesn't.

**Comment by yhatt** [comment]
The default preview does not been override even if you installed third-party extension. Thus, you can still open Marp preview. Try either of following:

- Use "Markdown: Open Preview" and "Markdown: Open preview to the Side" command directly from command palette. (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
- Change conflicted keybinding in [keyboard shortcuts editor](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor).
