### ISSUE TITLE
Could not export to PPTX (Marp for VS Code 0.10.1)

### ISSUE THREAD

**Issue by gaoyaoxin** [marp-team/marp-vscode#83]
To export slides to PPTX, I opened the quick picker from toolbar icon and typed "markdown.marp.exportType" but I found nothing. The "markdown.marp.export" gave no options for filetypes (e.g. PDF, PPTX). Only PDFs can be exported to. I am using VS Code version 1.33.0 and Marp for VS Code 0.10.1.

**Comment by yhatt** [comment]
`markdown.marp.exportType` is a key for preference and not command. 

![](https://user-images.githubusercontent.com/3993388/66705506-79598a80-ed62-11e9-938b-333988a152c8.png)

I'm sure the export type can choose from file format in `markdown.marp.export` dialog.

![](https://user-images.githubusercontent.com/3993388/66705545-32b86000-ed63-11e9-8b9b-294ac748a70a.png)

**Comment by gaoyaoxin** [comment]
Thanks. I found the default export type setting via Setting icon at the lower left corner -> Settings -> Extensions -> Marp for VS Code.
However, I can not see a type choosing menu when I click export button. See the screenshot below:
![DeepinScreenshot_select-area_20191013151137](https://user-images.githubusercontent.com/20694974/66712227-08e75380-edcc-11e9-98c5-d9248fffdd86.png)
I am using a VS Code version 1.33.0 and Marp for VS Code 0.10.1on a Linux (Deepin 15.11 Desktop Kernel 4.15.0-29deepin-generic), as follows.
![DeepinScreenshot_select-area_20191013151825](https://user-images.githubusercontent.com/20694974/66712276-de49ca80-edcc-11e9-9ee5-bb0db6cfbf30.png)
My file format choosing menu can be shown when I use a document editing software, as follows.
![DeepinScreenshot_select-area_20191013151928](https://user-images.githubusercontent.com/20694974/66712284-00434d00-edcd-11e9-95ba-1783685d9a9d.png)

**Comment by yhatt** [comment]
It might be an upstream issue by the unique window system from Deepin. Please report this to [VS Code](https://github.com/microsoft/vscode).

[Electron](https://github.com/electron/electron) has a similar issue (but it was not processing by not enough information): https://github.com/electron/electron/issues/20199

**Comment by yhatt** [comment]
NOTE: You might be already able to export to PPTX by adding `.pptx` extension to filename.

**Comment by gaoyaoxin** [comment]
> NOTE: You might be already able to export to PPTX by adding `.pptx` extension to filename.

Exporting, with or without a filetype extension (e.g. .pptx) could only lead to the default type as an output here on my computer.

**Comment by yhatt** [comment]
How about quoted filename such as `"foobar.pptx"`?

**Comment by gaoyaoxin** [comment]
> How about quoted filename such as `"foobar.pptx"`?
> 
> In any case, marp-vscode cannot solve this. Please report an issue to VS Code.

Quoted filename still led to a file in default type, but with a quotation mark at the beginning.
![DeepinScreenshot_dde-desktop_20191014083126](https://user-images.githubusercontent.com/20694974/66724895-f3226e80-ee5d-11e9-81bd-690833991851.png)
![DeepinScreenshot_dde-file-manager_20191014083256](https://user-images.githubusercontent.com/20694974/66724897-f4539b80-ee5d-11e9-8206-85a19e1dbd7f.png)
Thank you for your advice. I will report this to VS Code later.

**Comment by gaoyaoxin** [comment]
I unticked "Use the file chooser dialog of Deepin File Manager" in Setting -> Dialog of my Linux (Deepin) system's default file manager Deepin File Manager. Then I could chooser file types in Marp's exporting.
![DeepinScreenshot_dde-file-manager_20191014085053](https://user-images.githubusercontent.com/20694974/66725200-df790700-ee61-11e9-9c4a-224e61a1cb15.png)
![DeepinScreenshot_select-area_20191014085033](https://user-images.githubusercontent.com/20694974/66725203-e6077e80-ee61-11e9-8ef6-6e8bcfeaaef5.png)
In a post (https://bbs.deepin.org/forum.php?mod=viewthread&tid=178467) on deepin community, 4# gave two solutions to a filetype-not-shown problem on LibreOffice 6.1.6 (the other one is to add an extension such as .odt but this one did not work here on Marp). 2# reported that deb installed has this problem but flatpak does not.

**Comment by yhatt** [comment]
That's showing what it's an unique issue of your Linux distribution.

There are some workarounds and it cannot solve in Marp for VS Code. We have to focus into a problem for the extension so we close this.
