### ISSUE TITLE
Can't export in PDF using VS Code, Ubuntu, tmp file not found

### ISSUE THREAD

**Issue by eric-burel** [marp-team/marp-vscode#94]
Hi, I end up with this Error when running the export using VS Code
```
Failure to export. Marp CLI throwed unexpected error with exit code 1.
```
Any idea how I could get a more precise error message?
I run VS code 1.39.2 on Ubuntu 18
The rendering is otherwise fine in VS code, including using a custom theme.

I've installed the CLI + set my chrome path to Chromium (`/snap/bin/chromium`), without success.

In VS Code console I get `[ ERROR ] Failed converting Markdown. (net::ERR_FILE_NOT_FOUND at          file:///tmp/tmp-9409eYKvX0jV6Xfg.html)`
I don't have any HTML file in `/tmp`

If it can help, I also have this message: `[Embedded Page] Uncaught TypeError: Cannot assign to read only property 'className' of object '#<SVGSVGElement>'`

Note that I don't have the export options window screenshotted in the doc, I can't pick either pdf or html, I just get a system window asking for the filename.
Edit: it only affects PDF export, I can export in HTML

**Comment by yhatt** [comment]
Unfortunately we could not reproduce the reported error (`net::ERR_FILE_NOT_FOUND`) in our Ubuntu 18.10 + VS Code that was installed by snap.

The detail of error is as you see in developer console. Do you see the same result by exporting an empty Markdown into PDF?

**Comment by eric-burel** [comment]
Hi,
Thanks for trying a full repro.
Did you try using Chromium installed by snap?
I have the same result with an empty file.

Hopefully I can export in HTML then print as a palliative.

**Comment by yhatt** [comment]
Oh, I had tried in Google Chrome that was installed in [an official way](https://support.google.com/chrome/answer/95346). Later will try again with Chromium installed by snap.

Printing exported HTML should be a proper workaround at the moment.

**Comment by eric-burel** [comment]
Thinking about it, something that could affect the export is using an SSD. I have 2 partitions, one for Ubuntu and one for my Home. Maybe the CLI just don't have access to `/tmp` or can't find it ? But that sounds weird, I don't have such issues usually, so `/tmp` is probably already accessible by Marp. 

Just using the CLI outside of VS Code do not fail btw (it just fails to find images and theme, probably due to relative paths and how the VS code extension handles theme).

**Comment by yhatt** [comment]
I can't confirm it yet but apparently there is a similar issue in the other applications installed by snap.
https://forum.snapcraft.io/t/sharing-files-via-tmp/1613

Marp CLI is using inline HTML encoded by base64 to export PDF by default, and it would work (as you have confirmed). However, it fails to access to `file://` URI for local assets because of same-origin policy.

In VS Code extension, the built-in CLI will export PDF through a temporally HTML file created into `/tmp` for following `file://` same-origin policy. (It's as known as `--allow-local-files` in CLI)

**Comment by yhatt** [comment]
I've confirmed failing on Chromium and VS Code installed through snap, but thrown error was different from reported.

```
[ ERROR ] Failed converting Markdown. (Failed to launch chrome!
          
          
          TROUBLESHOOTING:
          https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
          )
```

A standalone Marp CLI is working with snapped Chromium in my environment too. My error could resolve by setting `markdown.marp.chromePath` to `/snap/chromium/current/usr/lib/chromium-browser/chrome`.

**Comment by eric-burel** [comment]
I'll try the `chromePath` you propose.
I confirm I cannot reproduce the issue on a machine with Chrome installed normally (so in `usr/bin`) with the same slide deck and config, in this case I get the .pdf.
At least there are a few workarounds, it's not a blocker.

**Comment by yhatt** [comment]
[A cause of issue](https://github.com/marp-team/marp-cli/issues/201) was fixed in the latest Marp CLI so the reported error not supposed to fail in [v0.12.1](https://github.com/marp-team/marp-vscode/releases/tag/v0.12.1). Please re-open the issue if still reproduces.

**Comment by ajformation** [comment]
> A standalone Marp CLI is working with snapped Chromium in my environment too. My error could resolve by setting `markdown.marp.chromePath` to `/snap/chromium/current/usr/lib/chromium-browser/chrome`.

YOU'RE A GENIUS !!!!!!

Thanks you so much !

**Comment by ajformation** [comment]
In fact you have to set : 

```json
"markdown.marp.browserPath": "/snap/chromium/current/usr/lib/chromium-browser/chrome"
```
