### ISSUE TITLE
Add rendering for keyboard shortcut

### ISSUE THREAD

**Issue by BuZZ-dEE** [marp-team/marp-vscode#95]
It would be great to have keyboard shortcuts rendered like e.g. here on GitHub.

<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>F1</kbd>

**Comment by yhatt** [comment]
Currently Marp for VS Code has not default shortcuts because we have to avoid conflicted keybinding against OS, VS Code and a lot of extensions (e.g. <kbd>Ctrl+Alt+F1</kbd> is already used in Linux environment to switch [virtual consoles](https://en.wikipedia.org/wiki/Virtual_console)).

We need the consensus of Marp community to implement default key binding.

**Comment by BuZZ-dEE** [comment]
The key binding above was just an example for the rendering.

**Comment by yhatt** [comment]
Uh-oh, we had misinterpreted your intention. Are you talking about the appearance of `<kbd>` tag, right?

Appearance has defined as Marp Core's built-in theme. Opening an issue in [marp-team/marp-core](https://github.com/marp-team/marp-core) would be better.

FYI: Marp Core's `default` theme is inherited from [GitHub CSS style](https://github.com/sindresorhus/github-markdown-css), so `<kbd>` should render with the appearance you expected. When you are using the other theme, you can tweak style like following:

```markdown
---
marp: true
theme: gaia
style: |
  kbd {
    background-color: #fafbfc;
    border: thin solid #d1d5da;
    border-bottom-color: #c6cbd1;
    border-radius: 0.2em;
    box-shadow: inset 0 -1px 0 #c6cbd1;
    color: #444d56;
    display: inline-block;
    font: 1em monospace;
    padding: 3px 5px;
    vertical-align: middle;
  }
---

<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>F1</kbd>
```

**Comment by BuZZ-dEE** [comment]
> Uh-oh, we had misinterpreted your intention. Are you talking about the appearance of `<kbd>` tag, right?

Yes

It is rendered like this:

![Bildschirmfoto vom 2019-11-10 21-48-54](https://user-images.githubusercontent.com/125954/68550581-51fae980-0404-11ea-9229-4e63a5474938.png)

Also if I add this:

```
---
marp: true
theme: gaia
style: |
  kbd {
    background-color: #fafbfc;
    border: thin solid #d1d5da;
    border-bottom-color: #c6cbd1;
    border-radius: 0.2em;
    box-shadow: inset 0 -1px 0 #c6cbd1;
    color: #444d56;
    display: inline-block;
    font: 1em monospace;
    padding: 3px 5px;
    vertical-align: middle;
  }
---
```

**Comment by yhatt** [comment]
Could you enable HTML from preference?

**Comment by BuZZ-dEE** [comment]
If I do that:

```
---
marp: true
theme: gaia
html: true
---
```

it does also not work.

**Comment by yhatt** [comment]
`html: true` is not correct way to enable HTML. (See https://github.com/marp-team/marpit/issues/198 for a reason)

You should enable HTML in VS Code setting as following. (https://github.com/marp-team/marpit/issues/162#issuecomment-490004489, https://github.com/marp-team/marpit/issues/178#issuecomment-511106762)

<img width="769" alt="HTML enable" src="https://user-images.githubusercontent.com/3993388/68582257-a8782e80-04bd-11ea-9a1d-3aa487de0b22.png">

**Comment by BuZZ-dEE** [comment]
thx, that solves my problem :)
