### ISSUE TITLE
Images that were changed on disk won't reload

### ISSUE THREAD

**Issue by pulkin** [marp-team/marp-vscode#96]
Clean installation of vscode and marp plugin on Fedora 31.

**Comment by yhatt** [comment]
VS Code (Electron) will cache image assets. Try to reload window manually. (<kbd>Ctrl+Shift+P</kbd> ▶️ Execute `Developer: Reload Window`)

**Comment by pulkin** [comment]
That works, thank you. Is it possible to limit caching?

**Comment by yhatt** [comment]
We have no idea. I think it's better to track the upstream issue for continuous talking about this problem: https://github.com/microsoft/vscode/issues/65258

**Comment by yhatt** [comment]
Good news! The markdown preview on the latest VS Code v1.53 has auto updation of images that were changed on disk. It's available in Marp preview too!
https://code.visualstudio.com/updates/v1_53#_markdown-preview-auto-updates-when-images-are-changed-on-disk

> :information_source: According to https://github.com/microsoft/vscode/pull/114083, the full auto updation is available only inline images (`![]()`, `<img src="">`). Background images like `![bg]()` and `<!-- backgroundImage: url('...') -->` are still required editing the content once to update preview.
