### ISSUE TITLE
Draw graphs via Marp VS Code

### ISSUE THREAD

**Issue by myvaheed** [marp-team/marp-vscode#97]
Is there ability to draw graphs? via, for example, as [here](https://shd101wyy.github.io/markdown-preview-enhanced/#/diagrams) . Or maybe we can use Markdown Preview Enhanced together?

**Comment by yhatt** [comment]
Marp for VS Code cannot draw graphs (charts). If you really want to extend the feature for any drawings, we recommend to use [Marp CLI](https://github.com/marp-team/marp-cli). It can customize rendering engine through plugins.

[Markdown Preview Enhanceed](https://github.com/shd101wyy/markdown-preview-enhanced) has own rendering so you would be better to make a request to MPE for supporting Marp (via [Marp Core](https://github.com/marp-team/marp-core))
